// <auto-generated/>
#nullable enable
using System; using System.Linq; using System.Threading; using System.Threading.Tasks; using System.Net.Http; using Flurl; using Flurl.Http; using System.Text.Json; using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal partial class ApiClient
{
    internal async Task DeleteProductGroupDeletegroupProductGroupIdAsync(DeleteProductGroupDeletegroupProductGroupIdRequest req, System.Threading.CancellationToken cancellationToken = default)
    {
        try
        {
            var path = "/ProductGroup/deletegroup/{productGroupId}";
            var __val_ProductGroupId = Convert.ToString(req.ProductGroupId, System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty;
            path = path.Replace("{productGroupId}", __val_ProductGroupId);
            path = path.Replace("{ProductGroupId}", __val_ProductGroupId);
            var url = new Url(_options.BaseUrl).AppendPathSegment(path.TrimStart('/'), false);
            var flreq = CreateRequest(url);
            var q = new System.Collections.Generic.Dictionary<string, object?>();
            if (q.Count > 0) flreq = flreq.SetQueryParams(q, Flurl.NullValueHandling.Remove);
            var resp = await flreq.SendAsync(new HttpMethod("DELETE"), null, completionOption: System.Net.Http.HttpCompletionOption.ResponseContentRead, cancellationToken: cancellationToken).ConfigureAwait(false);
            return;
        }
        catch (FlurlHttpException ex)
        {
            throw await BuildApiExceptionAsync(ex).ConfigureAwait(false);
        }
    }
}
