// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class DeleteInboundforecastGroupReferenceRequest
{
    public string? Reference { get; set; } = default!;
    public string? Sku { get; set; } = default!;
}
