// <auto-generated/>
#nullable enable
using System; using System.Linq; using System.Threading; using System.Threading.Tasks; using System.Net.Http; using Flurl; using Flurl.Http; using System.Text.Json; using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal partial class ApiClient
{
    internal async Task DeleteInboundforecastGroupReferenceSkuAsync(DeleteInboundforecastGroupReferenceSkuRequest req, System.Threading.CancellationToken cancellationToken = default)
    {
        try
        {
            var path = "/inboundforecast/group/{reference}/{sku}";
            var __val_Reference = Convert.ToString(req.Reference, System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty;
            path = path.Replace("{reference}", __val_Reference);
            path = path.Replace("{Reference}", __val_Reference);
            var __val_Sku = Convert.ToString(req.Sku, System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty;
            path = path.Replace("{sku}", __val_Sku);
            path = path.Replace("{Sku}", __val_Sku);
            var url = new Url(_options.BaseUrl).AppendPathSegment(path.TrimStart('/'), false);
            var flreq = CreateRequest(url);
            var q = new System.Collections.Generic.Dictionary<string, object?>();
            if (q.Count > 0) flreq = flreq.SetQueryParams(q, Flurl.NullValueHandling.Remove);
            var resp = await flreq.SendAsync(new HttpMethod("DELETE"), null, completionOption: System.Net.Http.HttpCompletionOption.ResponseContentRead, cancellationToken: cancellationToken).ConfigureAwait(false);
            return;
        }
        catch (FlurlHttpException ex)
        {
            throw await BuildApiExceptionAsync(ex).ConfigureAwait(false);
        }
    }
}
