// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class DeleteProductGroupDeletegroupProductGroupIdRequest
{
    public int? ProductGroupId { get; set; } = default!;
}
