// <auto-generated />
#nullable enable
namespace ApiConsoleClient.ApiClient;
internal partial class ApiClient
{
    private partial System.Collections.Generic.IEnumerable<string> GeneratedListOperationIds() => new [] {
        "DeleteInboundforecastGroupReference",
        "DeleteInboundforecastGroupReferenceSku",
        "DeleteOrderWebshoporderid",
        "DeleteProduct",
        "DeleteProductGroupDeletegroupProductGroupId",
        "DeleteProductSku",
        "DeleteProductSkuBarcode",
        "DeleteProductSkuBarcodeBarcode",
        "DeleteSupplierSuppliercode",
        "GetBatchGuidGuid",
        "GetHealth",
        "GetInboundforecastEventsSinceidId",
        "GetInboundforecastGroup",
        "GetInboundforecastGroupByproductskuProductsku",
        "GetInboundforecastGroupGuid",
        "GetInboundforecastGroupReference",
        "GetInboundforecastGroupReferenceLabel",
        "GetInboundforecastGroupReferenceSku",
        "GetInbounds",
        "GetInfo",
        "GetOrder",
        "GetOrdereventsSinceidId",
        "GetOrders",
        "GetOrderUpdatedsinceUpdatedSince",
        "GetOrderWebshoporderid",
        "GetOrderWebshoporderidBatches",
        "GetOrderWebshoporderidColli",
        "GetOrderWebshoporderidEvents",
        "GetOrderWebshoporderidExpectedprocessingtimeframe",
        "GetOrderWebshoporderidLinesdeleted",
        "GetOrderWebshoporderidReturn",
        "GetOrderWebshoporderidReturnforecasts",
        "GetOrderWebshoporderidReturnlabels",
        "GetOrderWebshoporderidSerials",
        "GetOrderWebshoporderidShippinglabels",
        "GetOrderWebshoporderidShippinglabelsFilename",
        "GetPickroutes",
        "GetProduct",
        "GetProductGroup",
        "GetProductGroupProductGroupId",
        "GetProductMateriaalIdImages",
        "GetProducts",
        "GetProductSku",
        "GetProductSkuStockIncludeSplitStock",
        "GetProductStock",
        "GetProductUpdatedsinceUpdatedSince",
        "GetPurchaseOrderGroup",
        "GetReports",
        "GetReportsIdFile",
        "GetReturnforecast",
        "GetReturnforecastCode",
        "GetReturnforecastCodeReturnlabel",
        "GetReturnId",
        "GetReturnIdDocuments",
        "GetReturnlabelchanges",
        "GetReturnlabelsTtcode",
        "GetReturnlabelsTtcodeChanges",
        "GetReturnreasons",
        "GetReturnSinceSince",
        "GetReturnUpdatedsinceSince",
        "GetSupplier",
        "GetSupplierSuppliercode",
        "PostAddress",
        "PostInboundforecastApprove",
        "PostInboundforecastGroup",
        "PostInboundforecastGroupReference",
        "PostOrder",
        "PostOrderActionsSplitWebshoporderid",
        "PostOrderWebshoporderidColli",
        "PostOrderWebshoporderidForget",
        "PostOrderWebshoporderidRmalinks",
        "PostOrderWebshoporderidShippinglabels",
        "PostProduct",
        "PostProductGroup",
        "PostProductSkuStockmutations",
        "PostReturnforecast",
        "PostShippingoptions",
        "PostSupplier",
        "PutInboundforecastGroupReference",
        "PutInboundforecastGroupReferenceSku",
        "PutOrderWebshoporderid",
        "PutProduct",
        "PutProductGroupAddProductGroupId",
        "PutProductGroupRemoveproductProductGroupId",
        "PutProductSku",
        "PutReturnforecastCode",
        "PutReturnIdUpdatereturnstatusMultiplelines",
        "PutReturnIdUpdatereturnstatusStatus",
        "PutSupplierSuppliercode",
    };

    private partial async System.Threading.Tasks.Task<object?> GeneratedExecuteAsync(string operationId, string? inputJson, System.Threading.CancellationToken cancellationToken)
    {
        switch (operationId)
        {
            case "PostAddress":
                var req_PostAddress = inputJson is null ? new PostAddressRequest() : System.Text.Json.JsonSerializer.Deserialize<PostAddressRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostAddress = await PostAddressAsync(req_PostAddress, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostAddress;
            case "GetBatchGuidGuid":
                var req_GetBatchGuidGuid = inputJson is null ? new GetBatchGuidGuidRequest() : System.Text.Json.JsonSerializer.Deserialize<GetBatchGuidGuidRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetBatchGuidGuid = await GetBatchGuidGuidAsync(req_GetBatchGuidGuid, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetBatchGuidGuid;
            case "GetHealth":
                var req_GetHealth = inputJson is null ? new GetHealthRequest() : System.Text.Json.JsonSerializer.Deserialize<GetHealthRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetHealth = await GetHealthAsync(req_GetHealth, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetHealth;
            case "GetInboundforecastGroupReferenceSku":
                var req_GetInboundforecastGroupReferenceSku = inputJson is null ? new GetInboundforecastGroupReferenceSkuRequest() : System.Text.Json.JsonSerializer.Deserialize<GetInboundforecastGroupReferenceSkuRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetInboundforecastGroupReferenceSku = await GetInboundforecastGroupReferenceSkuAsync(req_GetInboundforecastGroupReferenceSku, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetInboundforecastGroupReferenceSku;
            case "PutInboundforecastGroupReferenceSku":
                var req_PutInboundforecastGroupReferenceSku = inputJson is null ? new PutInboundforecastGroupReferenceSkuRequest() : System.Text.Json.JsonSerializer.Deserialize<PutInboundforecastGroupReferenceSkuRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutInboundforecastGroupReferenceSku = await PutInboundforecastGroupReferenceSkuAsync(req_PutInboundforecastGroupReferenceSku, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutInboundforecastGroupReferenceSku;
            case "DeleteInboundforecastGroupReferenceSku":
                var req_DeleteInboundforecastGroupReferenceSku = inputJson is null ? new DeleteInboundforecastGroupReferenceSkuRequest() : System.Text.Json.JsonSerializer.Deserialize<DeleteInboundforecastGroupReferenceSkuRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                await DeleteInboundforecastGroupReferenceSkuAsync(req_DeleteInboundforecastGroupReferenceSku, cancellationToken).ConfigureAwait(false);
                return null;
            case "GetInboundforecastEventsSinceidId":
                var req_GetInboundforecastEventsSinceidId = inputJson is null ? new GetInboundforecastEventsSinceidIdRequest() : System.Text.Json.JsonSerializer.Deserialize<GetInboundforecastEventsSinceidIdRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetInboundforecastEventsSinceidId = await GetInboundforecastEventsSinceidIdAsync(req_GetInboundforecastEventsSinceidId, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetInboundforecastEventsSinceidId;
            case "GetInboundforecastGroupReference":
                var req_GetInboundforecastGroupReference = inputJson is null ? new GetInboundforecastGroupReferenceRequest() : System.Text.Json.JsonSerializer.Deserialize<GetInboundforecastGroupReferenceRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetInboundforecastGroupReference = await GetInboundforecastGroupReferenceAsync(req_GetInboundforecastGroupReference, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetInboundforecastGroupReference;
            case "PostInboundforecastGroupReference":
                var req_PostInboundforecastGroupReference = inputJson is null ? new PostInboundforecastGroupReferenceRequest() : System.Text.Json.JsonSerializer.Deserialize<PostInboundforecastGroupReferenceRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostInboundforecastGroupReference = await PostInboundforecastGroupReferenceAsync(req_PostInboundforecastGroupReference, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostInboundforecastGroupReference;
            case "PutInboundforecastGroupReference":
                var req_PutInboundforecastGroupReference = inputJson is null ? new PutInboundforecastGroupReferenceRequest() : System.Text.Json.JsonSerializer.Deserialize<PutInboundforecastGroupReferenceRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutInboundforecastGroupReference = await PutInboundforecastGroupReferenceAsync(req_PutInboundforecastGroupReference, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutInboundforecastGroupReference;
            case "DeleteInboundforecastGroupReference":
                var req_DeleteInboundforecastGroupReference = inputJson is null ? new DeleteInboundforecastGroupReferenceRequest() : System.Text.Json.JsonSerializer.Deserialize<DeleteInboundforecastGroupReferenceRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                await DeleteInboundforecastGroupReferenceAsync(req_DeleteInboundforecastGroupReference, cancellationToken).ConfigureAwait(false);
                return null;
            case "GetInboundforecastGroupGuid":
                var req_GetInboundforecastGroupGuid = inputJson is null ? new GetInboundforecastGroupGuidRequest() : System.Text.Json.JsonSerializer.Deserialize<GetInboundforecastGroupGuidRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetInboundforecastGroupGuid = await GetInboundforecastGroupGuidAsync(req_GetInboundforecastGroupGuid, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetInboundforecastGroupGuid;
            case "GetInboundforecastGroup":
                var req_GetInboundforecastGroup = inputJson is null ? new GetInboundforecastGroupRequest() : System.Text.Json.JsonSerializer.Deserialize<GetInboundforecastGroupRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetInboundforecastGroup = await GetInboundforecastGroupAsync(req_GetInboundforecastGroup, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetInboundforecastGroup;
            case "PostInboundforecastGroup":
                var req_PostInboundforecastGroup = inputJson is null ? new PostInboundforecastGroupRequest() : System.Text.Json.JsonSerializer.Deserialize<PostInboundforecastGroupRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostInboundforecastGroup = await PostInboundforecastGroupAsync(req_PostInboundforecastGroup, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostInboundforecastGroup;
            case "GetInboundforecastGroupReferenceLabel":
                var req_GetInboundforecastGroupReferenceLabel = inputJson is null ? new GetInboundforecastGroupReferenceLabelRequest() : System.Text.Json.JsonSerializer.Deserialize<GetInboundforecastGroupReferenceLabelRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetInboundforecastGroupReferenceLabel = await GetInboundforecastGroupReferenceLabelAsync(req_GetInboundforecastGroupReferenceLabel, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetInboundforecastGroupReferenceLabel;
            case "GetInboundforecastGroupByproductskuProductsku":
                var req_GetInboundforecastGroupByproductskuProductsku = inputJson is null ? new GetInboundforecastGroupByproductskuProductskuRequest() : System.Text.Json.JsonSerializer.Deserialize<GetInboundforecastGroupByproductskuProductskuRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetInboundforecastGroupByproductskuProductsku = await GetInboundforecastGroupByproductskuProductskuAsync(req_GetInboundforecastGroupByproductskuProductsku, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetInboundforecastGroupByproductskuProductsku;
            case "PostInboundforecastApprove":
                var req_PostInboundforecastApprove = inputJson is null ? new PostInboundforecastApproveRequest() : System.Text.Json.JsonSerializer.Deserialize<PostInboundforecastApproveRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostInboundforecastApprove = await PostInboundforecastApproveAsync(req_PostInboundforecastApprove, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostInboundforecastApprove;
            case "GetInbounds":
                var req_GetInbounds = inputJson is null ? new GetInboundsRequest() : System.Text.Json.JsonSerializer.Deserialize<GetInboundsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetInbounds = await GetInboundsAsync(req_GetInbounds, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetInbounds;
            case "GetInfo":
                var req_GetInfo = inputJson is null ? new GetInfoRequest() : System.Text.Json.JsonSerializer.Deserialize<GetInfoRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetInfo = await GetInfoAsync(req_GetInfo, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetInfo;
            case "GetOrderWebshoporderid":
                var req_GetOrderWebshoporderid = inputJson is null ? new GetOrderWebshoporderidRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderid = await GetOrderWebshoporderidAsync(req_GetOrderWebshoporderid, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderid;
            case "PutOrderWebshoporderid":
                var req_PutOrderWebshoporderid = inputJson is null ? new PutOrderWebshoporderidRequest() : System.Text.Json.JsonSerializer.Deserialize<PutOrderWebshoporderidRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutOrderWebshoporderid = await PutOrderWebshoporderidAsync(req_PutOrderWebshoporderid, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutOrderWebshoporderid;
            case "DeleteOrderWebshoporderid":
                var req_DeleteOrderWebshoporderid = inputJson is null ? new DeleteOrderWebshoporderidRequest() : System.Text.Json.JsonSerializer.Deserialize<DeleteOrderWebshoporderidRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                await DeleteOrderWebshoporderidAsync(req_DeleteOrderWebshoporderid, cancellationToken).ConfigureAwait(false);
                return null;
            case "GetOrderUpdatedsinceUpdatedSince":
                var req_GetOrderUpdatedsinceUpdatedSince = inputJson is null ? new GetOrderUpdatedsinceUpdatedSinceRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderUpdatedsinceUpdatedSinceRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderUpdatedsinceUpdatedSince = await GetOrderUpdatedsinceUpdatedSinceAsync(req_GetOrderUpdatedsinceUpdatedSince, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderUpdatedsinceUpdatedSince;
            case "GetOrders":
                var req_GetOrders = inputJson is null ? new GetOrdersRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrdersRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrders = await GetOrdersAsync(req_GetOrders, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrders;
            case "GetOrder":
                var req_GetOrder = inputJson is null ? new GetOrderRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrder = await GetOrderAsync(req_GetOrder, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrder;
            case "PostOrder":
                var req_PostOrder = inputJson is null ? new PostOrderRequest() : System.Text.Json.JsonSerializer.Deserialize<PostOrderRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostOrder = await PostOrderAsync(req_PostOrder, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostOrder;
            case "PostOrderWebshoporderidForget":
                var req_PostOrderWebshoporderidForget = inputJson is null ? new PostOrderWebshoporderidForgetRequest() : System.Text.Json.JsonSerializer.Deserialize<PostOrderWebshoporderidForgetRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostOrderWebshoporderidForget = await PostOrderWebshoporderidForgetAsync(req_PostOrderWebshoporderidForget, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostOrderWebshoporderidForget;
            case "GetOrderWebshoporderidReturn":
                var req_GetOrderWebshoporderidReturn = inputJson is null ? new GetOrderWebshoporderidReturnRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidReturnRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidReturn = await GetOrderWebshoporderidReturnAsync(req_GetOrderWebshoporderidReturn, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidReturn;
            case "GetOrderWebshoporderidSerials":
                var req_GetOrderWebshoporderidSerials = inputJson is null ? new GetOrderWebshoporderidSerialsRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidSerialsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidSerials = await GetOrderWebshoporderidSerialsAsync(req_GetOrderWebshoporderidSerials, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidSerials;
            case "GetOrderWebshoporderidReturnforecasts":
                var req_GetOrderWebshoporderidReturnforecasts = inputJson is null ? new GetOrderWebshoporderidReturnforecastsRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidReturnforecastsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidReturnforecasts = await GetOrderWebshoporderidReturnforecastsAsync(req_GetOrderWebshoporderidReturnforecasts, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidReturnforecasts;
            case "GetOrderWebshoporderidReturnlabels":
                var req_GetOrderWebshoporderidReturnlabels = inputJson is null ? new GetOrderWebshoporderidReturnlabelsRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidReturnlabelsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidReturnlabels = await GetOrderWebshoporderidReturnlabelsAsync(req_GetOrderWebshoporderidReturnlabels, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidReturnlabels;
            case "GetOrderWebshoporderidEvents":
                var req_GetOrderWebshoporderidEvents = inputJson is null ? new GetOrderWebshoporderidEventsRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidEventsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidEvents = await GetOrderWebshoporderidEventsAsync(req_GetOrderWebshoporderidEvents, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidEvents;
            case "GetOrderWebshoporderidLinesdeleted":
                var req_GetOrderWebshoporderidLinesdeleted = inputJson is null ? new GetOrderWebshoporderidLinesdeletedRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidLinesdeletedRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidLinesdeleted = await GetOrderWebshoporderidLinesdeletedAsync(req_GetOrderWebshoporderidLinesdeleted, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidLinesdeleted;
            case "PostOrderWebshoporderidColli":
                var req_PostOrderWebshoporderidColli = inputJson is null ? new PostOrderWebshoporderidColliRequest() : System.Text.Json.JsonSerializer.Deserialize<PostOrderWebshoporderidColliRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostOrderWebshoporderidColli = await PostOrderWebshoporderidColliAsync(req_PostOrderWebshoporderidColli, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostOrderWebshoporderidColli;
            case "GetOrderWebshoporderidColli":
                var req_GetOrderWebshoporderidColli = inputJson is null ? new GetOrderWebshoporderidColliRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidColliRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidColli = await GetOrderWebshoporderidColliAsync(req_GetOrderWebshoporderidColli, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidColli;
            case "PostOrderWebshoporderidShippinglabels":
                var req_PostOrderWebshoporderidShippinglabels = inputJson is null ? new PostOrderWebshoporderidShippinglabelsRequest() : System.Text.Json.JsonSerializer.Deserialize<PostOrderWebshoporderidShippinglabelsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostOrderWebshoporderidShippinglabels = await PostOrderWebshoporderidShippinglabelsAsync(req_PostOrderWebshoporderidShippinglabels, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostOrderWebshoporderidShippinglabels;
            case "GetOrderWebshoporderidShippinglabels":
                var req_GetOrderWebshoporderidShippinglabels = inputJson is null ? new GetOrderWebshoporderidShippinglabelsRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidShippinglabelsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidShippinglabels = await GetOrderWebshoporderidShippinglabelsAsync(req_GetOrderWebshoporderidShippinglabels, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidShippinglabels;
            case "GetOrderWebshoporderidBatches":
                var req_GetOrderWebshoporderidBatches = inputJson is null ? new GetOrderWebshoporderidBatchesRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidBatchesRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidBatches = await GetOrderWebshoporderidBatchesAsync(req_GetOrderWebshoporderidBatches, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidBatches;
            case "GetOrderWebshoporderidShippinglabelsFilename":
                var req_GetOrderWebshoporderidShippinglabelsFilename = inputJson is null ? new GetOrderWebshoporderidShippinglabelsFilenameRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidShippinglabelsFilenameRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidShippinglabelsFilename = await GetOrderWebshoporderidShippinglabelsFilenameAsync(req_GetOrderWebshoporderidShippinglabelsFilename, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidShippinglabelsFilename;
            case "PostOrderWebshoporderidRmalinks":
                var req_PostOrderWebshoporderidRmalinks = inputJson is null ? new PostOrderWebshoporderidRmalinksRequest() : System.Text.Json.JsonSerializer.Deserialize<PostOrderWebshoporderidRmalinksRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostOrderWebshoporderidRmalinks = await PostOrderWebshoporderidRmalinksAsync(req_PostOrderWebshoporderidRmalinks, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostOrderWebshoporderidRmalinks;
            case "GetOrderWebshoporderidExpectedprocessingtimeframe":
                var req_GetOrderWebshoporderidExpectedprocessingtimeframe = inputJson is null ? new GetOrderWebshoporderidExpectedprocessingtimeframeRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrderWebshoporderidExpectedprocessingtimeframeRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrderWebshoporderidExpectedprocessingtimeframe = await GetOrderWebshoporderidExpectedprocessingtimeframeAsync(req_GetOrderWebshoporderidExpectedprocessingtimeframe, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrderWebshoporderidExpectedprocessingtimeframe;
            case "PostOrderActionsSplitWebshoporderid":
                var req_PostOrderActionsSplitWebshoporderid = inputJson is null ? new PostOrderActionsSplitWebshoporderidRequest() : System.Text.Json.JsonSerializer.Deserialize<PostOrderActionsSplitWebshoporderidRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostOrderActionsSplitWebshoporderid = await PostOrderActionsSplitWebshoporderidAsync(req_PostOrderActionsSplitWebshoporderid, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostOrderActionsSplitWebshoporderid;
            case "GetOrdereventsSinceidId":
                var req_GetOrdereventsSinceidId = inputJson is null ? new GetOrdereventsSinceidIdRequest() : System.Text.Json.JsonSerializer.Deserialize<GetOrdereventsSinceidIdRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetOrdereventsSinceidId = await GetOrdereventsSinceidIdAsync(req_GetOrdereventsSinceidId, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetOrdereventsSinceidId;
            case "GetPickroutes":
                var req_GetPickroutes = inputJson is null ? new GetPickroutesRequest() : System.Text.Json.JsonSerializer.Deserialize<GetPickroutesRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetPickroutes = await GetPickroutesAsync(req_GetPickroutes, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetPickroutes;
            case "GetProductSku":
                var req_GetProductSku = inputJson is null ? new GetProductSkuRequest() : System.Text.Json.JsonSerializer.Deserialize<GetProductSkuRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetProductSku = await GetProductSkuAsync(req_GetProductSku, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetProductSku;
            case "PutProductSku":
                var req_PutProductSku = inputJson is null ? new PutProductSkuRequest() : System.Text.Json.JsonSerializer.Deserialize<PutProductSkuRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutProductSku = await PutProductSkuAsync(req_PutProductSku, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutProductSku;
            case "DeleteProductSku":
                var req_DeleteProductSku = inputJson is null ? new DeleteProductSkuRequest() : System.Text.Json.JsonSerializer.Deserialize<DeleteProductSkuRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                await DeleteProductSkuAsync(req_DeleteProductSku, cancellationToken).ConfigureAwait(false);
                return null;
            case "GetProduct":
                var req_GetProduct = inputJson is null ? new GetProductRequest() : System.Text.Json.JsonSerializer.Deserialize<GetProductRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetProduct = await GetProductAsync(req_GetProduct, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetProduct;
            case "PostProduct":
                var req_PostProduct = inputJson is null ? new PostProductRequest() : System.Text.Json.JsonSerializer.Deserialize<PostProductRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostProduct = await PostProductAsync(req_PostProduct, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostProduct;
            case "PutProduct":
                var req_PutProduct = inputJson is null ? new PutProductRequest() : System.Text.Json.JsonSerializer.Deserialize<PutProductRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutProduct = await PutProductAsync(req_PutProduct, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutProduct;
            case "DeleteProduct":
                var req_DeleteProduct = inputJson is null ? new DeleteProductRequest() : System.Text.Json.JsonSerializer.Deserialize<DeleteProductRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                await DeleteProductAsync(req_DeleteProduct, cancellationToken).ConfigureAwait(false);
                return null;
            case "GetProductStock":
                var req_GetProductStock = inputJson is null ? new GetProductStockRequest() : System.Text.Json.JsonSerializer.Deserialize<GetProductStockRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetProductStock = await GetProductStockAsync(req_GetProductStock, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetProductStock;
            case "GetProductSkuStockIncludeSplitStock":
                var req_GetProductSkuStockIncludeSplitStock = inputJson is null ? new GetProductSkuStockIncludeSplitStockRequest() : System.Text.Json.JsonSerializer.Deserialize<GetProductSkuStockIncludeSplitStockRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetProductSkuStockIncludeSplitStock = await GetProductSkuStockIncludeSplitStockAsync(req_GetProductSkuStockIncludeSplitStock, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetProductSkuStockIncludeSplitStock;
            case "GetProductUpdatedsinceUpdatedSince":
                var req_GetProductUpdatedsinceUpdatedSince = inputJson is null ? new GetProductUpdatedsinceUpdatedSinceRequest() : System.Text.Json.JsonSerializer.Deserialize<GetProductUpdatedsinceUpdatedSinceRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetProductUpdatedsinceUpdatedSince = await GetProductUpdatedsinceUpdatedSinceAsync(req_GetProductUpdatedsinceUpdatedSince, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetProductUpdatedsinceUpdatedSince;
            case "DeleteProductSkuBarcodeBarcode":
                var req_DeleteProductSkuBarcodeBarcode = inputJson is null ? new DeleteProductSkuBarcodeBarcodeRequest() : System.Text.Json.JsonSerializer.Deserialize<DeleteProductSkuBarcodeBarcodeRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                await DeleteProductSkuBarcodeBarcodeAsync(req_DeleteProductSkuBarcodeBarcode, cancellationToken).ConfigureAwait(false);
                return null;
            case "DeleteProductSkuBarcode":
                var req_DeleteProductSkuBarcode = inputJson is null ? new DeleteProductSkuBarcodeRequest() : System.Text.Json.JsonSerializer.Deserialize<DeleteProductSkuBarcodeRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                await DeleteProductSkuBarcodeAsync(req_DeleteProductSkuBarcode, cancellationToken).ConfigureAwait(false);
                return null;
            case "GetProducts":
                var req_GetProducts = inputJson is null ? new GetProductsRequest() : System.Text.Json.JsonSerializer.Deserialize<GetProductsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetProducts = await GetProductsAsync(req_GetProducts, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetProducts;
            case "PostProductSkuStockmutations":
                var req_PostProductSkuStockmutations = inputJson is null ? new PostProductSkuStockmutationsRequest() : System.Text.Json.JsonSerializer.Deserialize<PostProductSkuStockmutationsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostProductSkuStockmutations = await PostProductSkuStockmutationsAsync(req_PostProductSkuStockmutations, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostProductSkuStockmutations;
            case "GetProductMateriaalIdImages":
                var req_GetProductMateriaalIdImages = inputJson is null ? new GetProductMateriaalIdImagesRequest() : System.Text.Json.JsonSerializer.Deserialize<GetProductMateriaalIdImagesRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetProductMateriaalIdImages = await GetProductMateriaalIdImagesAsync(req_GetProductMateriaalIdImages, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetProductMateriaalIdImages;
            case "GetProductGroup":
                var req_GetProductGroup = inputJson is null ? new GetProductGroupRequest() : System.Text.Json.JsonSerializer.Deserialize<GetProductGroupRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetProductGroup = await GetProductGroupAsync(req_GetProductGroup, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetProductGroup;
            case "PostProductGroup":
                var req_PostProductGroup = inputJson is null ? new PostProductGroupRequest() : System.Text.Json.JsonSerializer.Deserialize<PostProductGroupRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostProductGroup = await PostProductGroupAsync(req_PostProductGroup, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostProductGroup;
            case "GetProductGroupProductGroupId":
                var req_GetProductGroupProductGroupId = inputJson is null ? new GetProductGroupProductGroupIdRequest() : System.Text.Json.JsonSerializer.Deserialize<GetProductGroupProductGroupIdRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetProductGroupProductGroupId = await GetProductGroupProductGroupIdAsync(req_GetProductGroupProductGroupId, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetProductGroupProductGroupId;
            case "PutProductGroupAddProductGroupId":
                var req_PutProductGroupAddProductGroupId = inputJson is null ? new PutProductGroupAddProductGroupIdRequest() : System.Text.Json.JsonSerializer.Deserialize<PutProductGroupAddProductGroupIdRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutProductGroupAddProductGroupId = await PutProductGroupAddProductGroupIdAsync(req_PutProductGroupAddProductGroupId, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutProductGroupAddProductGroupId;
            case "PutProductGroupRemoveproductProductGroupId":
                var req_PutProductGroupRemoveproductProductGroupId = inputJson is null ? new PutProductGroupRemoveproductProductGroupIdRequest() : System.Text.Json.JsonSerializer.Deserialize<PutProductGroupRemoveproductProductGroupIdRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutProductGroupRemoveproductProductGroupId = await PutProductGroupRemoveproductProductGroupIdAsync(req_PutProductGroupRemoveproductProductGroupId, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutProductGroupRemoveproductProductGroupId;
            case "DeleteProductGroupDeletegroupProductGroupId":
                var req_DeleteProductGroupDeletegroupProductGroupId = inputJson is null ? new DeleteProductGroupDeletegroupProductGroupIdRequest() : System.Text.Json.JsonSerializer.Deserialize<DeleteProductGroupDeletegroupProductGroupIdRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                await DeleteProductGroupDeletegroupProductGroupIdAsync(req_DeleteProductGroupDeletegroupProductGroupId, cancellationToken).ConfigureAwait(false);
                return null;
            case "GetPurchaseOrderGroup":
                var req_GetPurchaseOrderGroup = inputJson is null ? new GetPurchaseOrderGroupRequest() : System.Text.Json.JsonSerializer.Deserialize<GetPurchaseOrderGroupRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetPurchaseOrderGroup = await GetPurchaseOrderGroupAsync(req_GetPurchaseOrderGroup, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetPurchaseOrderGroup;
            case "GetReports":
                var req_GetReports = inputJson is null ? new GetReportsRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReportsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReports = await GetReportsAsync(req_GetReports, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReports;
            case "GetReportsIdFile":
                var req_GetReportsIdFile = inputJson is null ? new GetReportsIdFileRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReportsIdFileRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReportsIdFile = await GetReportsIdFileAsync(req_GetReportsIdFile, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReportsIdFile;
            case "GetReturnId":
                var req_GetReturnId = inputJson is null ? new GetReturnIdRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnIdRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnId = await GetReturnIdAsync(req_GetReturnId, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnId;
            case "GetReturnSinceSince":
                var req_GetReturnSinceSince = inputJson is null ? new GetReturnSinceSinceRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnSinceSinceRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnSinceSince = await GetReturnSinceSinceAsync(req_GetReturnSinceSince, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnSinceSince;
            case "GetReturnUpdatedsinceSince":
                var req_GetReturnUpdatedsinceSince = inputJson is null ? new GetReturnUpdatedsinceSinceRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnUpdatedsinceSinceRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnUpdatedsinceSince = await GetReturnUpdatedsinceSinceAsync(req_GetReturnUpdatedsinceSince, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnUpdatedsinceSince;
            case "GetReturnIdDocuments":
                var req_GetReturnIdDocuments = inputJson is null ? new GetReturnIdDocumentsRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnIdDocumentsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnIdDocuments = await GetReturnIdDocumentsAsync(req_GetReturnIdDocuments, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnIdDocuments;
            case "PutReturnIdUpdatereturnstatusStatus":
                var req_PutReturnIdUpdatereturnstatusStatus = inputJson is null ? new PutReturnIdUpdatereturnstatusStatusRequest() : System.Text.Json.JsonSerializer.Deserialize<PutReturnIdUpdatereturnstatusStatusRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutReturnIdUpdatereturnstatusStatus = await PutReturnIdUpdatereturnstatusStatusAsync(req_PutReturnIdUpdatereturnstatusStatus, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutReturnIdUpdatereturnstatusStatus;
            case "PutReturnIdUpdatereturnstatusMultiplelines":
                var req_PutReturnIdUpdatereturnstatusMultiplelines = inputJson is null ? new PutReturnIdUpdatereturnstatusMultiplelinesRequest() : System.Text.Json.JsonSerializer.Deserialize<PutReturnIdUpdatereturnstatusMultiplelinesRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutReturnIdUpdatereturnstatusMultiplelines = await PutReturnIdUpdatereturnstatusMultiplelinesAsync(req_PutReturnIdUpdatereturnstatusMultiplelines, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutReturnIdUpdatereturnstatusMultiplelines;
            case "PostReturnforecast":
                var req_PostReturnforecast = inputJson is null ? new PostReturnforecastRequest() : System.Text.Json.JsonSerializer.Deserialize<PostReturnforecastRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostReturnforecast = await PostReturnforecastAsync(req_PostReturnforecast, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostReturnforecast;
            case "GetReturnforecast":
                var req_GetReturnforecast = inputJson is null ? new GetReturnforecastRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnforecastRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnforecast = await GetReturnforecastAsync(req_GetReturnforecast, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnforecast;
            case "GetReturnforecastCode":
                var req_GetReturnforecastCode = inputJson is null ? new GetReturnforecastCodeRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnforecastCodeRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnforecastCode = await GetReturnforecastCodeAsync(req_GetReturnforecastCode, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnforecastCode;
            case "PutReturnforecastCode":
                var req_PutReturnforecastCode = inputJson is null ? new PutReturnforecastCodeRequest() : System.Text.Json.JsonSerializer.Deserialize<PutReturnforecastCodeRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutReturnforecastCode = await PutReturnforecastCodeAsync(req_PutReturnforecastCode, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutReturnforecastCode;
            case "GetReturnforecastCodeReturnlabel":
                var req_GetReturnforecastCodeReturnlabel = inputJson is null ? new GetReturnforecastCodeReturnlabelRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnforecastCodeReturnlabelRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnforecastCodeReturnlabel = await GetReturnforecastCodeReturnlabelAsync(req_GetReturnforecastCodeReturnlabel, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnforecastCodeReturnlabel;
            case "GetReturnreasons":
                var req_GetReturnreasons = inputJson is null ? new GetReturnreasonsRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnreasonsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnreasons = await GetReturnreasonsAsync(req_GetReturnreasons, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnreasons;
            case "GetReturnlabelsTtcode":
                var req_GetReturnlabelsTtcode = inputJson is null ? new GetReturnlabelsTtcodeRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnlabelsTtcodeRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnlabelsTtcode = await GetReturnlabelsTtcodeAsync(req_GetReturnlabelsTtcode, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnlabelsTtcode;
            case "GetReturnlabelsTtcodeChanges":
                var req_GetReturnlabelsTtcodeChanges = inputJson is null ? new GetReturnlabelsTtcodeChangesRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnlabelsTtcodeChangesRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnlabelsTtcodeChanges = await GetReturnlabelsTtcodeChangesAsync(req_GetReturnlabelsTtcodeChanges, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnlabelsTtcodeChanges;
            case "GetReturnlabelchanges":
                var req_GetReturnlabelchanges = inputJson is null ? new GetReturnlabelchangesRequest() : System.Text.Json.JsonSerializer.Deserialize<GetReturnlabelchangesRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetReturnlabelchanges = await GetReturnlabelchangesAsync(req_GetReturnlabelchanges, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetReturnlabelchanges;
            case "PostShippingoptions":
                var req_PostShippingoptions = inputJson is null ? new PostShippingoptionsRequest() : System.Text.Json.JsonSerializer.Deserialize<PostShippingoptionsRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostShippingoptions = await PostShippingoptionsAsync(req_PostShippingoptions, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostShippingoptions;
            case "GetSupplierSuppliercode":
                var req_GetSupplierSuppliercode = inputJson is null ? new GetSupplierSuppliercodeRequest() : System.Text.Json.JsonSerializer.Deserialize<GetSupplierSuppliercodeRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetSupplierSuppliercode = await GetSupplierSuppliercodeAsync(req_GetSupplierSuppliercode, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetSupplierSuppliercode;
            case "PutSupplierSuppliercode":
                var req_PutSupplierSuppliercode = inputJson is null ? new PutSupplierSuppliercodeRequest() : System.Text.Json.JsonSerializer.Deserialize<PutSupplierSuppliercodeRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PutSupplierSuppliercode = await PutSupplierSuppliercodeAsync(req_PutSupplierSuppliercode, cancellationToken).ConfigureAwait(false);
                return (object?)res_PutSupplierSuppliercode;
            case "DeleteSupplierSuppliercode":
                var req_DeleteSupplierSuppliercode = inputJson is null ? new DeleteSupplierSuppliercodeRequest() : System.Text.Json.JsonSerializer.Deserialize<DeleteSupplierSuppliercodeRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                await DeleteSupplierSuppliercodeAsync(req_DeleteSupplierSuppliercode, cancellationToken).ConfigureAwait(false);
                return null;
            case "GetSupplier":
                var req_GetSupplier = inputJson is null ? new GetSupplierRequest() : System.Text.Json.JsonSerializer.Deserialize<GetSupplierRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_GetSupplier = await GetSupplierAsync(req_GetSupplier, cancellationToken).ConfigureAwait(false);
                return (object?)res_GetSupplier;
            case "PostSupplier":
                var req_PostSupplier = inputJson is null ? new PostSupplierRequest() : System.Text.Json.JsonSerializer.Deserialize<PostSupplierRequest>(inputJson, ApiConsoleClient.ApiClient.JsonOptions.Default)!;
                var res_PostSupplier = await PostSupplierAsync(req_PostSupplier, cancellationToken).ConfigureAwait(false);
                return (object?)res_PostSupplier;
            default: throw new System.ArgumentOutOfRangeException(nameof(operationId), operationId, "Unknown operationId");
        }
    }
}
