// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetBatchGuidGuidRequest
{
    public string? Guid { get; set; } = default!;
}
