// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetInboundforecastGroupByproductskuProductskuRequest
{
    public string? Productsku { get; set; } = default!;
}
