// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetInfoRequest
{
    public string? Origin { get; set; } = default!;
}
