// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetOrderUpdatedsinceUpdatedSinceRequest
{
    public System.DateTimeOffset? UpdatedSince { get; set; } = default!;
    public MontaRestApiModels_Orders_ReadUpdatedSinceStatusEnum? Status { get; set; } = default!;
}
