// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetOrderWebshoporderidExpectedprocessingtimeframeRequest
{
    public string? Webshoporderid { get; set; } = default!;
}
