// <auto-generated/>
#nullable enable
using System; using System.Linq; using System.Threading; using System.Threading.Tasks; using System.Net.Http; using Flurl; using Flurl.Http; using System.Text.Json; using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal partial class ApiClient
{
    internal async Task<MontaRESTApiModels_Product_Product> GetProductAsync(GetProductRequest req, System.Threading.CancellationToken cancellationToken = default)
    {
        try
        {
            var path = "/product";
            var url = new Url(_options.BaseUrl).AppendPathSegment(path.TrimStart('/'), false);
            var flreq = CreateRequest(url);
            var q = new System.Collections.Generic.Dictionary<string, object?>();
            if (req.Barcode is not null) q["barcode"] = Convert.ToString(req.Barcode, System.Globalization.CultureInfo.InvariantCulture);
            if (req.Sku is not null) q["sku"] = Convert.ToString(req.Sku, System.Globalization.CultureInfo.InvariantCulture);
            if (q.Count > 0) flreq = flreq.SetQueryParams(q, Flurl.NullValueHandling.Remove);
            var resp = await flreq.SendAsync(new HttpMethod("GET"), null, completionOption: System.Net.Http.HttpCompletionOption.ResponseContentRead, cancellationToken: cancellationToken).ConfigureAwait(false);
            return await ReadJsonAsync<MontaRESTApiModels_Product_Product>(resp).ConfigureAwait(false);
        }
        catch (FlurlHttpException ex)
        {
            throw await BuildApiExceptionAsync(ex).ConfigureAwait(false);
        }
    }
}
