// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetPurchaseOrderGroupRequest
{
    public System.DateTimeOffset? CreationDate { get; set; } = default!;
    public int? Page { get; set; } = default!;
}
