// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetProductUpdatedsinceUpdatedSinceRequest
{
    public System.DateTimeOffset? UpdatedSince { get; set; } = default!;
}
