// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetProductMateriaalIdImagesRequest
{
    public int? MateriaalId { get; set; } = default!;
}
