// <auto-generated/>
#nullable enable
using System; using System.Linq; using System.Threading; using System.Threading.Tasks; using System.Net.Http; using Flurl; using Flurl.Http; using System.Text.Json; using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal partial class ApiClient
{
    internal async Task<MontaRESTApiModels_Product_Product> GetProductSkuStockIncludeSplitStockAsync(GetProductSkuStockIncludeSplitStockRequest req, System.Threading.CancellationToken cancellationToken = default)
    {
        try
        {
            var path = "/product/{sku}/stock/{includeSplitStock}";
            var __val_Sku = Convert.ToString(req.Sku, System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty;
            path = path.Replace("{sku}", __val_Sku);
            path = path.Replace("{Sku}", __val_Sku);
            var __val_IncludeSplitStock = (Convert.ToString(req.IncludeSplitStock) ?? string.Empty).ToLowerInvariant();
            path = path.Replace("{includeSplitStock}", __val_IncludeSplitStock);
            path = path.Replace("{IncludeSplitStock}", __val_IncludeSplitStock);
            var url = new Url(_options.BaseUrl).AppendPathSegment(path.TrimStart('/'), false);
            var flreq = CreateRequest(url);
            var q = new System.Collections.Generic.Dictionary<string, object?>();
            if (q.Count > 0) flreq = flreq.SetQueryParams(q, Flurl.NullValueHandling.Remove);
            var resp = await flreq.SendAsync(new HttpMethod("GET"), null, completionOption: System.Net.Http.HttpCompletionOption.ResponseContentRead, cancellationToken: cancellationToken).ConfigureAwait(false);
            return await ReadJsonAsync<MontaRESTApiModels_Product_Product>(resp).ConfigureAwait(false);
        }
        catch (FlurlHttpException ex)
        {
            throw await BuildApiExceptionAsync(ex).ConfigureAwait(false);
        }
    }
}
