// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetPickroutesRequest
{
    public System.DateTimeOffset? AssignedSince { get; set; } = default!;
}
