// <auto-generated/>
#nullable enable
using System; using System.Linq; using System.Threading; using System.Threading.Tasks; using System.Net.Http; using Flurl; using Flurl.Http; using System.Text.Json; using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal partial class ApiClient
{
    internal async Task<MontaRESTApiModels_ReturnForecast_ReturnForecast> GetReturnforecastCodeAsync(GetReturnforecastCodeRequest req, System.Threading.CancellationToken cancellationToken = default)
    {
        try
        {
            var path = "/returnforecast/{code}";
            var __val_Code = Convert.ToString(req.Code, System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty;
            path = path.Replace("{code}", __val_Code);
            path = path.Replace("{Code}", __val_Code);
            var url = new Url(_options.BaseUrl).AppendPathSegment(path.TrimStart('/'), false);
            var flreq = CreateRequest(url);
            var q = new System.Collections.Generic.Dictionary<string, object?>();
            if (q.Count > 0) flreq = flreq.SetQueryParams(q, Flurl.NullValueHandling.Remove);
            var resp = await flreq.SendAsync(new HttpMethod("GET"), null, completionOption: System.Net.Http.HttpCompletionOption.ResponseContentRead, cancellationToken: cancellationToken).ConfigureAwait(false);
            return await ReadJsonAsync<MontaRESTApiModels_ReturnForecast_ReturnForecast>(resp).ConfigureAwait(false);
        }
        catch (FlurlHttpException ex)
        {
            throw await BuildApiExceptionAsync(ex).ConfigureAwait(false);
        }
    }
}
