// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetReportsRequest
{
    public System.DateTimeOffset? CreatedAfter { get; set; } = default!;
}
