// <auto-generated/>
#nullable enable
using System; using System.Linq; using System.Threading; using System.Threading.Tasks; using System.Net.Http; using Flurl; using Flurl.Http; using System.Text.Json; using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal partial class ApiClient
{
    internal async Task<MontaRestApiModels_Dto_ReturnDto> GetReturnUpdatedsinceSinceAsync(GetReturnUpdatedsinceSinceRequest req, System.Threading.CancellationToken cancellationToken = default)
    {
        try
        {
            var path = "/return/updated_since/{since}";
            var __val_Since = req.Since is null ? string.Empty : ((System.DateTimeOffset)req.Since).ToString("yyyy-MM-ddTHH:mm:ssK", System.Globalization.CultureInfo.InvariantCulture);
            path = path.Replace("{since}", __val_Since);
            path = path.Replace("{Since}", __val_Since);
            var url = new Url(_options.BaseUrl).AppendPathSegment(path.TrimStart('/'), false);
            var flreq = CreateRequest(url);
            var q = new System.Collections.Generic.Dictionary<string, object?>();
            if (req.Status is not null) q["status"] = Convert.ToString(req.Status, System.Globalization.CultureInfo.InvariantCulture);
            if (q.Count > 0) flreq = flreq.SetQueryParams(q, Flurl.NullValueHandling.Remove);
            var resp = await flreq.SendAsync(new HttpMethod("GET"), null, completionOption: System.Net.Http.HttpCompletionOption.ResponseContentRead, cancellationToken: cancellationToken).ConfigureAwait(false);
            return await ReadJsonAsync<MontaRestApiModels_Dto_ReturnDto>(resp).ConfigureAwait(false);
        }
        catch (FlurlHttpException ex)
        {
            throw await BuildApiExceptionAsync(ex).ConfigureAwait(false);
        }
    }
}
