// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetReturnSinceSinceRequest
{
    public System.DateTimeOffset? Since { get; set; } = default!;
    public string? Status { get; set; } = default!;
}
