// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetReturnlabelsTtcodeRequest
{
    public string? Ttcode { get; set; } = default!;
}
