// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetReturnforecastRequest
{
    public System.DateTimeOffset? CreatedSince { get; set; } = default!;
    public System.DateTimeOffset? CreatedUntil { get; set; } = default!;
    public int? Page { get; set; } = default!;
    public int? PageSize { get; set; } = default!;
    public bool? GetCountOnly { get; set; } = default!;
}
