// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetReturnforecastCodeReturnlabelRequest
{
    public string? Code { get; set; } = default!;
    public string? ShipperCode { get; set; } = default!;
}
