// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class GetSupplierSuppliercodeRequest
{
    public string? Suppliercode { get; set; } = default!;
}
