// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostOrderActionsSplitWebshoporderidRequest
{
    public string? Webshoporderid { get; set; } = default!;
    public System.Collections.Generic.List<MontaRestApiModels_Orders_SplitOrders_SplitOrderRequestLine>? Body { get; set; } = default!;
}
