// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostOrderWebshoporderidShippinglabelsRequest
{
    public string? Webshoporderid { get; set; } = default!;
    public string? Labelfiletype { get; set; } = default!;
}
