// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostProductRequest
{
    public MontaRESTApiModels_Product_Product? Body { get; set; } = default!;
}
