// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostInboundforecastGroupRequest
{
    public MontaRESTApiModels_InboundForecast_InboundForecastGroup? Body { get; set; } = default!;
}
