// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostOrderRequest
{
    public MontaRESTApiModels_Orders_Order? Body { get; set; } = default!;
}
