// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostShippingoptionsRequest
{
    public MontaRESTApiModels_ShippingOptions_IndexParameters? Body { get; set; } = default!;
}
