// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostProductGroupRequest
{
    public MontaRESTApiModels_ProductGroups_ProductGroupPostDTO? Body { get; set; } = default!;
}
