// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostOrderWebshoporderidColliRequest
{
    public string? Webshoporderid { get; set; } = default!;
    public MontaRESTApiModels_Orders_Collo? Body { get; set; } = default!;
}
