// <auto-generated/>
#nullable enable
using System; using System.Linq; using System.Threading; using System.Threading.Tasks; using System.Net.Http; using Flurl; using Flurl.Http; using System.Text.Json; using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal partial class ApiClient
{
    internal async Task<object> PostOrderWebshoporderidForgetAsync(PostOrderWebshoporderidForgetRequest req, System.Threading.CancellationToken cancellationToken = default)
    {
        try
        {
            var path = "/order/{webshoporderid}/forget";
            var __val_Webshoporderid = Convert.ToString(req.Webshoporderid, System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty;
            path = path.Replace("{webshoporderid}", __val_Webshoporderid);
            path = path.Replace("{Webshoporderid}", __val_Webshoporderid);
            var url = new Url(_options.BaseUrl).AppendPathSegment(path.TrimStart('/'), false);
            var flreq = CreateRequest(url);
            var q = new System.Collections.Generic.Dictionary<string, object?>();
            if (req.Invoice is not null) q["invoice"] = (Convert.ToString(req.Invoice) ?? string.Empty).ToLowerInvariant();
            if (req.Shipping is not null) q["shipping"] = (Convert.ToString(req.Shipping) ?? string.Empty).ToLowerInvariant();
            if (q.Count > 0) flreq = flreq.SetQueryParams(q, Flurl.NullValueHandling.Remove);
            var resp = await flreq.SendAsync(new HttpMethod("POST"), null, completionOption: System.Net.Http.HttpCompletionOption.ResponseContentRead, cancellationToken: cancellationToken).ConfigureAwait(false);
            return await ReadJsonAsync<object>(resp).ConfigureAwait(false);
        }
        catch (FlurlHttpException ex)
        {
            throw await BuildApiExceptionAsync(ex).ConfigureAwait(false);
        }
    }
}
