// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostSupplierRequest
{
    public MontaRESTApiModels_Supplier_Supplier? Body { get; set; } = default!;
}
