// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostOrderWebshoporderidForgetRequest
{
    public string? Webshoporderid { get; set; } = default!;
    public bool? Invoice { get; set; } = default!;
    public bool? Shipping { get; set; } = default!;
}
