// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PostProductSkuStockmutationsRequest
{
    public string? Sku { get; set; } = default!;
    public MontaRESTApiModels_StockMutation? Body { get; set; } = default!;
}
