// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PutInboundforecastGroupReferenceSkuRequest
{
    public string? Reference { get; set; } = default!;
    public string? Sku { get; set; } = default!;
    public bool? AddQtyToExisting { get; set; } = default!;
    public MontaRESTApiModels_InboundForecast_UpdateInboundForecast? Body { get; set; } = default!;
}
