// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PutInboundforecastGroupReferenceRequest
{
    public string? Reference { get; set; } = default!;
    public MontaRESTApiModels_InboundForecast_UpdateInboundForecastGroup? Body { get; set; } = default!;
}
