// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PutProductGroupRemoveproductProductGroupIdRequest
{
    public int? ProductGroupId { get; set; } = default!;
    public System.Collections.Generic.List<int>? Body { get; set; } = default!;
}
