// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PutProductSkuRequest
{
    public string? Sku { get; set; } = default!;
    public MontaRESTApiModels_Product_UpdateProduct? Body { get; set; } = default!;
}
