// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PutReturnforecastCodeRequest
{
    public string? Code { get; set; } = default!;
    public MontaRESTApiModels_ReturnForecast_ReturnForecast? Body { get; set; } = default!;
}
