// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PutReturnIdUpdatereturnstatusMultiplelinesRequest
{
    public int? Id { get; set; } = default!;
    public System.Collections.Generic.List<MontaRESTApiModels_Return_LineToUpdateStatusOf>? Body { get; set; } = default!;
}
