// <auto-generated/>
#nullable enable
using System; using System.Linq; using System.Threading; using System.Threading.Tasks; using System.Net.Http; using Flurl; using Flurl.Http; using System.Text.Json; using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal partial class ApiClient
{
    internal async Task<string> PutReturnIdUpdatereturnstatusMultiplelinesAsync(PutReturnIdUpdatereturnstatusMultiplelinesRequest req, System.Threading.CancellationToken cancellationToken = default)
    {
        try
        {
            var path = "/return/{id}/update_return_status/multiple_lines";
            var __val_Id = Convert.ToString(req.Id, System.Globalization.CultureInfo.InvariantCulture) ?? string.Empty;
            path = path.Replace("{id}", __val_Id);
            path = path.Replace("{Id}", __val_Id);
            var url = new Url(_options.BaseUrl).AppendPathSegment(path.TrimStart('/'), false);
            var flreq = CreateRequest(url);
            var q = new System.Collections.Generic.Dictionary<string, object?>();
            if (q.Count > 0) flreq = flreq.SetQueryParams(q, Flurl.NullValueHandling.Remove);
            var resp = await flreq.SendJsonAsync(new HttpMethod("PUT"), req.Body!, cancellationToken: cancellationToken).ConfigureAwait(false);
            return await ReadJsonAsync<string>(resp).ConfigureAwait(false);
        }
        catch (FlurlHttpException ex)
        {
            throw await BuildApiExceptionAsync(ex).ConfigureAwait(false);
        }
    }
}
