// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
using ApiConsoleClient.Models;
namespace ApiConsoleClient.ApiClient;
internal sealed class PutSupplierSuppliercodeRequest
{
    public string? Suppliercode { get; set; } = default!;
    public MontaRESTApiModels_Supplier_UpdateSupplier? Body { get; set; } = default!;
}
