// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class Microsoft_AspNetCore_Mvc_ProblemDetails
{
    [JsonPropertyName("Type")] public string? Type { get; set; } = default!;
    [JsonPropertyName("Title")] public string? Title { get; set; } = default!;
    [JsonPropertyName("Status")] public int? Status { get; set; } = default!;
    [JsonPropertyName("Detail")] public string? Detail { get; set; } = default!;
    [JsonPropertyName("Instance")] public string? Instance { get; set; } = default!;
}
