// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_InboundForecast_InboundForecastGroupReceivedDate
{
    [JsonPropertyName("From")] public System.DateTimeOffset? From { get; set; } = default!;
    [JsonPropertyName("To")] public System.DateTimeOffset? To { get; set; } = default!;
}
