// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Return_ReturnLine
{
    [JsonPropertyName("LineId")] public int? LineId { get; set; } = default!;
    [JsonPropertyName("WebshopOrderLineId")] public string? WebshopOrderLineId { get; set; } = default!;
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("ReturnedQuantity")] public int? ReturnedQuantity { get; set; } = default!;
    [JsonPropertyName("Sellable")] public bool? Sellable { get; set; } = default!;
    [JsonPropertyName("FollowedUpMontapacking")] public bool? FollowedUpMontapacking { get; set; } = default!;
    [JsonPropertyName("FollowedUpCustomer")] public bool? FollowedUpCustomer { get; set; } = default!;
    [JsonPropertyName("FollowedUpAction")] public MontaRESTApiModels_Return_FollowedUpAction? FollowedUpAction { get; set; } = default!;
    [JsonPropertyName("Cause")] public string? Cause { get; set; } = default!;
    [JsonPropertyName("Comment")] public string? Comment { get; set; } = default!;
    [JsonPropertyName("BatchCode")] public string? BatchCode { get; set; } = default!;
    [JsonPropertyName("OrderLineGuid")] public string? OrderLineGuid { get; set; } = default!;
}
