// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_OrderInvalidReasonsResponse
{
    [JsonPropertyName("OrderInvalidReasons")] public System.Collections.Generic.List<MontaRESTApiModels_Orders_OrderInvalidReason>? OrderInvalidReasons { get; set; } = default!;
}
