// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ReturnForecast_ReturnForecastLine
{
    [JsonPropertyName("WebshopOrderLineId")] public string? WebshopOrderLineId { get; set; } = default!;
    [JsonPropertyName("ReturnQuantity")] public int ReturnQuantity { get; set; } = default!;
    [JsonPropertyName("ReturnReason")] public string? ReturnReason { get; set; } = default!;
    [JsonPropertyName("RelatieRetourOorzaakId")] public int? RelatieRetourOorzaakId { get; set; } = default!;
    [JsonPropertyName("RelatieRetourOorzaakParentId")] public int? RelatieRetourOorzaakParentId { get; set; } = default!;
    [JsonPropertyName("CustomerComment")] public string? CustomerComment { get; set; } = default!;
    [JsonPropertyName("OrderlineGuid")] public string? OrderlineGuid { get; set; } = default!;
}
