// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_OrderDeleteInvalidReasonsResponse
{
    [JsonPropertyName("OrderDeleteInvalidReasons")] public System.Collections.Generic.List<MontaRESTApiModels_Orders_OrderDeleteInvalidReason>? OrderDeleteInvalidReasons { get; set; } = default!;
}
