// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModel_WMS_Materialen_ProductGroups_Models_ProductGroupBlockedDescriptionTranslation
{
    [JsonPropertyName("Id")] public int? Id { get; set; } = default!;
    [JsonPropertyName("ProductGroupId")] public int? ProductGroupId { get; set; } = default!;
    [JsonPropertyName("Language")] public string? Language { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
}
