// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Return_Return
{
    [JsonPropertyName("Id")] public int? Id { get; set; } = default!;
    [JsonPropertyName("CreatedAt")] public System.DateTimeOffset? CreatedAt { get; set; } = default!;
    [JsonPropertyName("Comment")] public string? Comment { get; set; } = default!;
    [JsonPropertyName("Cause")] public string? Cause { get; set; } = default!;
    [JsonPropertyName("WebshopCause")] public string? WebshopCause { get; set; } = default!;
    [JsonPropertyName("WebshopOrderId")] public string? WebshopOrderId { get; set; } = default!;
    [JsonPropertyName("Lines")] public System.Collections.Generic.List<MontaRESTApiModels_Return_ReturnLine>? Lines { get; set; } = default!;
    [JsonPropertyName("UpdatedAt")] public System.DateTimeOffset? UpdatedAt { get; set; } = default!;
    [JsonPropertyName("SerialNumbers")] public System.Collections.Generic.List<MontaRESTApiModels_Return_SerialNo>? SerialNumbers { get; set; } = default!;
    [JsonPropertyName("ReturnForecastId")] public int? ReturnForecastId { get; set; } = default!;
    [JsonPropertyName("ForecastCode")] public string? ForecastCode { get; set; } = default!;
}
