// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_InboundForecastInvalidReasonsResponse
{
    [JsonPropertyName("ForecastInvalidReasons")] public System.Collections.Generic.List<MontaRESTApiModels_InboundForecast_InboundForecastInvalidReason>? ForecastInvalidReasons { get; set; } = default!;
}
