// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Info_Origin
{
    [JsonPropertyName("Name")] public string? Name { get; set; } = default!;
    [JsonPropertyName("IsDemo")] public string? IsDemo { get; set; } = default!;
    [JsonPropertyName("ShipperOptions")] public System.Collections.Generic.List<MontaRESTApiModels_Info_ShipperInfo>? ShipperOptions { get; set; } = default!;
    [JsonPropertyName("SurpriseCodes")] public System.Collections.Generic.List<string>? SurpriseCodes { get; set; } = default!;
}
