// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_Invoice
{
    [JsonPropertyName("PaymentMethodDescription")] public string? PaymentMethodDescription { get; set; } = default!;
    [JsonPropertyName("AmountInclTax")] public double? AmountInclTax { get; set; } = default!;
    [JsonPropertyName("TotalTax")] public double? TotalTax { get; set; } = default!;
    [JsonPropertyName("Paid")] public bool Paid { get; set; } = default!;
    [JsonPropertyName("WebshopFactuurID")] public string WebshopFactuurID { get; set; } = default!;
    [JsonPropertyName("Currency")] public string Currency { get; set; } = default!;
    [JsonPropertyName("Lines")] public System.Collections.Generic.List<MontaRESTApiModels_Orders_InvoiceLine>? Lines { get; set; } = default!;
    [JsonPropertyName("HasData")] public bool? HasData { get; set; } = default!;
    [JsonPropertyName("BTWNummer")] public string? BTWNummer { get; set; } = default!;
    [JsonPropertyName("EORINummer")] public string? EORINummer { get; set; } = default!;
}
