// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ProductGroups_ProductGroupPostDTO
{
    [JsonPropertyName("GroupName")] public string? GroupName { get; set; } = default!;
    [JsonPropertyName("IdsOfProducts")] public System.Collections.Generic.List<int>? IdsOfProducts { get; set; } = default!;
    [JsonPropertyName("UsedForTradeIn")] public bool? UsedForTradeIn { get; set; } = default!;
}
