// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Return_UpdateMultipleLineStatusErrorReturn
{
    [JsonPropertyName("ErrorMessage")] public string? ErrorMessage { get; set; } = default!;
    [JsonPropertyName("InvalidReasons")] public System.Collections.Generic.List<string>? InvalidReasons { get; set; } = default!;
}
