// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
[JsonConverter(typeof(JsonStringEnumConverter))]
internal enum MontaModel_Efulfillment_Eorders_EorderHeader_PickStatus
{
    NotReady = 0,
    Warehouse = 1,
    PickToLight = 2,
    MultipleFloors = 3,
    NotManuallyAccessible = 4,
    Unknown = 5,
    EcheckLocations = 6,
    WaitingInTransport = 7,
    Highcare = 8,
    DelayBetweenLinkingAndPicking = 9,
    FullPalletPossible = 10,
    FullPalletManuallyAccessible = 11,
    FullPalletNotManuallyAccessible = 12,
    PartialPalletNotManuallyAccessible = 13,
    Runner = 14,
    RunnerHighcare = 15,
    B2BCrossdock = 16,
    B2B = 17,
    B2BHighcare = 18,
    Montapacker = 19,
    AutoStore = 20,
    PalletDC = 21,
}
