// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Product_UpdateProduct
{
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
    [JsonPropertyName("Barcodes")] public System.Collections.Generic.List<string>? Barcodes { get; set; } = default!;
    [JsonPropertyName("ProductBarcodes")] public System.Collections.Generic.List<MontaRESTApiModels_Product_ProductBarcode>? ProductBarcodes { get; set; } = default!;
    [JsonPropertyName("WeightGrammes")] public int? WeightGrammes { get; set; } = default!;
    [JsonPropertyName("LengthMm")] public int? LengthMm { get; set; } = default!;
    [JsonPropertyName("WidthMm")] public int? WidthMm { get; set; } = default!;
    [JsonPropertyName("HeightMm")] public int? HeightMm { get; set; } = default!;
    [JsonPropertyName("ImageUrl")] public string? ImageUrl { get; set; } = default!;
    [JsonPropertyName("Stock")] public MontaRESTApiModels_Product_Stock? Stock { get; set; } = default!;
    [JsonPropertyName("SupplierCode")] public string? SupplierCode { get; set; } = default!;
    [JsonPropertyName("PurchasePrice")] public double? PurchasePrice { get; set; } = default!;
    [JsonPropertyName("SellingPrice")] public double? SellingPrice { get; set; } = default!;
    [JsonPropertyName("PurchasePriceHidden")] public double? PurchasePriceHidden { get; set; } = default!;
    [JsonPropertyName("Food")] public bool? Food { get; set; } = default!;
    [JsonPropertyName("MinimumExpiryPeriodInbound")] public int? MinimumExpiryPeriodInbound { get; set; } = default!;
    [JsonPropertyName("MinimumExpiryPeriodOutbound")] public int? MinimumExpiryPeriodOutbound { get; set; } = default!;
    [JsonPropertyName("Cool")] public bool? Cool { get; set; } = default!;
    [JsonPropertyName("Note")] public string? Note { get; set; } = default!;
    [JsonPropertyName("HStariefCode")] public string? HStariefCode { get; set; } = default!;
    [JsonPropertyName("CountryOfOrigin")] public string? CountryOfOrigin { get; set; } = default!;
    [JsonPropertyName("PurchaseStepQty")] public int? PurchaseStepQty { get; set; } = default!;
    [JsonPropertyName("RegisterSerialNumber")] public bool? RegisterSerialNumber { get; set; } = default!;
    [JsonPropertyName("RegisterSerialNumberB2B")] public bool? RegisterSerialNumberB2B { get; set; } = default!;
    [JsonPropertyName("IsFragile")] public bool? IsFragile { get; set; } = default!;
    [JsonPropertyName("IsDangerous")] public bool? IsDangerous { get; set; } = default!;
    [JsonPropertyName("SupplierProductCode")] public string? SupplierProductCode { get; set; } = default!;
    [JsonPropertyName("MinimumStock")] public int? MinimumStock { get; set; } = default!;
    [JsonPropertyName("HSCode")] public string? HSCode { get; set; } = default!;
    [JsonPropertyName("WareHouseProductSettings")] public System.Collections.Generic.List<MontaRestApiModels_Product_WarehouseProductSettings>? WareHouseProductSettings { get; set; } = default!;
    [JsonPropertyName("ProductId")] public int? ProductId { get; set; } = default!;
    [JsonPropertyName("HTSCode")] public string? HTSCode { get; set; } = default!;
    [JsonPropertyName("CustomField1")] public string? CustomField1 { get; set; } = default!;
    [JsonPropertyName("SoldPerWeekAverage")] public double? SoldPerWeekAverage { get; set; } = default!;
    [JsonPropertyName("ExcludeFromStockForecast")] public bool? ExcludeFromStockForecast { get; set; } = default!;
    [JsonPropertyName("BatchNonFood")] public bool? BatchNonFood { get; set; } = default!;
    [JsonPropertyName("LeadTime")] public int? LeadTime { get; set; } = default!;
}
