// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModel_Efulfillment_Returns_Forecasts_Line
{
    [JsonPropertyName("Id")] public int? Id { get; set; } = default!;
    [JsonPropertyName("ReturnForecastId")] public int? ReturnForecastId { get; set; } = default!;
    [JsonPropertyName("ProductCode")] public string? ProductCode { get; set; } = default!;
    [JsonPropertyName("ProductDescription")] public string? ProductDescription { get; set; } = default!;
    [JsonPropertyName("MateriaalId")] public int? MateriaalId { get; set; } = default!;
    [JsonPropertyName("ReturnReasonId")] public int? ReturnReasonId { get; set; } = default!;
    [JsonPropertyName("RelatieReturnReasonId")] public int? RelatieReturnReasonId { get; set; } = default!;
    [JsonPropertyName("ParentRelatieReturnReasonId")] public int? ParentRelatieReturnReasonId { get; set; } = default!;
    [JsonPropertyName("ReturnReason")] public string? ReturnReason { get; set; } = default!;
    [JsonPropertyName("ReturnSubReasonId")] public int? ReturnSubReasonId { get; set; } = default!;
    [JsonPropertyName("ReturnSubReason")] public string? ReturnSubReason { get; set; } = default!;
    [JsonPropertyName("Comment")] public string? Comment { get; set; } = default!;
    [JsonPropertyName("EorderLineId")] public int? EorderLineId { get; set; } = default!;
    [JsonPropertyName("ReturnQuantity")] public int? ReturnQuantity { get; set; } = default!;
    [JsonPropertyName("Reference")] public string? Reference { get; set; } = default!;
    [JsonPropertyName("FollowUpActionId")] public int? FollowUpActionId { get; set; } = default!;
    [JsonPropertyName("ForecastLineTradeInProduct")] public MontaModel_Efulfillment_Returns_Forecasts_Forecasts_models_ForecastLineTradeInProduct? ForecastLineTradeInProduct { get; set; } = default!;
}
