// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModel_Efulfillment_Eorders_ForecastedProduct
{
    [JsonPropertyName("ExpectedForecastDeliveryDate")] public System.DateTimeOffset? ExpectedForecastDeliveryDate { get; set; } = default!;
    [JsonPropertyName("InboundForecastGroupId")] public int? InboundForecastGroupId { get; set; } = default!;
    [JsonPropertyName("InboundForecastGroupReference")] public string? InboundForecastGroupReference { get; set; } = default!;
    [JsonPropertyName("Quantity")] public int? Quantity { get; set; } = default!;
}
