// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_ProductGroups_ProductGroupInvalidReason
{
    [JsonPropertyName("Code")] public int? Code { get; set; } = default!;
    [JsonPropertyName("Message")] public string? Message { get; set; } = default!;
}
