// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_FamilyMember
{
    [JsonPropertyName("WebshopOrderID")] public string WebshopOrderID { get; set; } = default!;
    [JsonPropertyName("Reason")] public string Reason { get; set; } = default!;
}
