// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_PickupPointDetails
{
    [JsonPropertyName("Code")] public string? Code { get; set; } = default!;
    [JsonPropertyName("DistanceMeters")] public double? DistanceMeters { get; set; } = default!;
    [JsonPropertyName("Company")] public string? Company { get; set; } = default!;
    [JsonPropertyName("Street")] public string? Street { get; set; } = default!;
    [JsonPropertyName("HouseNumber")] public string? HouseNumber { get; set; } = default!;
    [JsonPropertyName("PostalCode")] public string? PostalCode { get; set; } = default!;
    [JsonPropertyName("District")] public string? District { get; set; } = default!;
    [JsonPropertyName("City")] public string? City { get; set; } = default!;
    [JsonPropertyName("State")] public string? State { get; set; } = default!;
    [JsonPropertyName("CountryCode")] public string? CountryCode { get; set; } = default!;
    [JsonPropertyName("AddressRemark")] public string? AddressRemark { get; set; } = default!;
    [JsonPropertyName("Phone")] public string? Phone { get; set; } = default!;
    [JsonPropertyName("Longitude")] public double? Longitude { get; set; } = default!;
    [JsonPropertyName("Latitude")] public double? Latitude { get; set; } = default!;
    [JsonPropertyName("ImageUrl")] public string? ImageUrl { get; set; } = default!;
    [JsonPropertyName("OpeningTimes")] public System.Collections.Generic.List<MontaModelShippers_Generic_Pickup_PickupPointOpeningTimes>? OpeningTimes { get; set; } = default!;
}
