// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModelShippers_Generic_Pickup_OpeningTimes
{
    [JsonPropertyName("From")] public string? From { get; set; } = default!;
    [JsonPropertyName("To")] public string? To { get; set; } = default!;
}
