// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Info_ShipperInfo
{
    [JsonPropertyName("ShipperDescription")] public string? ShipperDescription { get; set; } = default!;
    [JsonPropertyName("ShipperCode")] public string? ShipperCode { get; set; } = default!;
    [JsonPropertyName("IsMailbox")] public bool? IsMailbox { get; set; } = default!;
    [JsonPropertyName("IsPickupPoint")] public bool? IsPickupPoint { get; set; } = default!;
    [JsonPropertyName("AvailableInShippingOptions")] public bool? AvailableInShippingOptions { get; set; } = default!;
    [JsonPropertyName("DisplayName")] public string? DisplayName { get; set; } = default!;
    [JsonPropertyName("ActiveInCheckout")] public bool? ActiveInCheckout { get; set; } = default!;
}
