// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Dto_ReturnDocumentsDto
{
    [JsonPropertyName("ReturnDocuments")] public System.Collections.Generic.List<MontaRESTApiModels_Return_ReturnDocument>? ReturnDocuments { get; set; } = default!;
}
