// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Dto_OrdersDto
{
    [JsonPropertyName("Orders")] public System.Collections.Generic.List<MontaRestApiModels_Dto_OrderDto>? Orders { get; set; } = default!;
}
