// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApi_Classes_Batches_BatchLine
{
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("Quantity")] public int? Quantity { get; set; } = default!;
    [JsonPropertyName("BatchContent")] public MontaModel_WMS_Batches_Batch? BatchContent { get; set; } = default!;
}
