// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Dto_ReturnDto
{
    [JsonPropertyName("Returns")] public System.Collections.Generic.List<MontaRESTApiModels_Return_Return>? Returns { get; set; } = default!;
}
