// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_ReturnLabel_ReturnLabelChange
{
    [JsonPropertyName("Id")] public int? Id { get; set; } = default!;
    [JsonPropertyName("LabelTtCode")] public string? LabelTtCode { get; set; } = default!;
    [JsonPropertyName("OccuredUtc")] public System.DateTimeOffset? OccuredUtc { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusCode")] public string? DeliveryStatusCode { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusDescription")] public string? DeliveryStatusDescription { get; set; } = default!;
    [JsonPropertyName("ShipperStatusCode")] public string? ShipperStatusCode { get; set; } = default!;
    [JsonPropertyName("ShipperStatusDescription")] public string? ShipperStatusDescription { get; set; } = default!;
}
