// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_ConsumerDetails
{
    [JsonPropertyName("DeliveryAddress")] public MontaRESTApiModels_Orders_ContactDetails DeliveryAddress { get; set; } = default!;
    [JsonPropertyName("InvoiceAddress")] public MontaRESTApiModels_Orders_ContactDetails? InvoiceAddress { get; set; } = default!;
    [JsonPropertyName("InvoiceDebtorNumber")] public string? InvoiceDebtorNumber { get; set; } = default!;
    [JsonPropertyName("B2B")] public bool B2B { get; set; } = default!;
    [JsonPropertyName("ShippingComment")] public string? ShippingComment { get; set; } = default!;
    [JsonPropertyName("CommunicationLanguageCode")] public string? CommunicationLanguageCode { get; set; } = default!;
}
