// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_ProductGroups_ProductGroupInvalidReasonsResponse
{
    [JsonPropertyName("ProductGroupInvalidReasons")] public System.Collections.Generic.List<MontaRestApiModels_ProductGroups_ProductGroupInvalidReason>? ProductGroupInvalidReasons { get; set; } = default!;
}
