// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_ReturnLabel_ReturnLabel
{
    [JsonPropertyName("ShipperDescription")] public string? ShipperDescription { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceCode")] public string? TrackAndTraceCode { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceLink")] public string? TrackAndTraceLink { get; set; } = default!;
    [JsonPropertyName("Created")] public System.DateTimeOffset? Created { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusCode")] public string? DeliveryStatusCode { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusDescription")] public string? DeliveryStatusDescription { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusChangedUtc")] public System.DateTimeOffset? DeliveryStatusChangedUtc { get; set; } = default!;
    [JsonPropertyName("EnRouteUtc")] public System.DateTimeOffset? EnRouteUtc { get; set; } = default!;
    [JsonPropertyName("DeliveredUtc")] public System.DateTimeOffset? DeliveredUtc { get; set; } = default!;
}
