// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_InboundForecast_UpdateInboundForecastGroup
{
    [JsonPropertyName("Reference")] public string? Reference { get; set; } = default!;
    [JsonPropertyName("InboundForecasts")] public System.Collections.Generic.List<MontaRESTApiModels_InboundForecast_UpdateInboundForecast>? InboundForecasts { get; set; } = default!;
    [JsonPropertyName("SupplierCode")] public string? SupplierCode { get; set; } = default!;
    [JsonPropertyName("Comment")] public string? Comment { get; set; } = default!;
    [JsonPropertyName("WarehouseDisplayName")] public string? WarehouseDisplayName { get; set; } = default!;
    [JsonPropertyName("Created")] public System.DateTimeOffset? Created { get; set; } = default!;
    [JsonPropertyName("AllocateStockOnDelivery")] public bool? AllocateStockOnDelivery { get; set; } = default!;
    [JsonPropertyName("ExpectedDeliveryDate")] public System.DateTimeOffset? ExpectedDeliveryDate { get; set; } = default!;
    [JsonPropertyName("DeliveryDate")] public System.DateTimeOffset? DeliveryDate { get; set; } = default!;
    [JsonPropertyName("ReceivedDate")] public MontaRestApiModels_InboundForecast_InboundForecastGroupReceivedDate? ReceivedDate { get; set; } = default!;
    [JsonPropertyName("UniqueId")] public string? UniqueId { get; set; } = default!;
}
