// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
[JsonConverter(typeof(JsonStringEnumConverter))]
internal enum MontaModel_Efulfillment_Eorders_EorderHeader_MailboxShipperMandatoryType
{
    None = 0,
    MailboxShipperMandatory = 1,
    NonMailboxShipperMandatory = 2,
}
