// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
[JsonConverter(typeof(JsonStringEnumConverter))]
internal enum MontaRestApiModels_InboundForecast_InboundForecastEventCode
{
    ForecastCreated = 0,
    Received = 1,
    ForecastStatusChanged = 2,
    ExpectedDeliveryDateChanged = 3,
    DeliveryDeleted = 4,
    ApprovalStatusChanged = 5,
    ApprovalStatusNotChanged = 6,
    QuantityChanged = 7,
    NewBatchCreated = 8,
    CommentChanged = 9,
    ReferenceChanged = 10,
    LineAdded = 11,
}
