// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_ImpossibleShipperOption
{
    [JsonPropertyName("ShipperCode")] public string? ShipperCode { get; set; } = default!;
    [JsonPropertyName("Reasons")] public System.Collections.Generic.List<MontaRESTApiModels_ShippingOptions_ImpossibleShipperOptionReason>? Reasons { get; set; } = default!;
}
