// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApi_Classes_Batches_BatchResult
{
    [JsonPropertyName("WebshopOrderId")] public string? WebshopOrderId { get; set; } = default!;
    [JsonPropertyName("DateTimeCreation")] public System.DateTimeOffset? DateTimeCreation { get; set; } = default!;
    [JsonPropertyName("BatchLines")] public System.Collections.Generic.List<MontaRESTApi_Classes_Batches_BatchLine>? BatchLines { get; set; } = default!;
}
