// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
[JsonConverter(typeof(JsonStringEnumConverter))]
internal enum MontaModel_Efulfillment_Eorders_EorderHeader_VerwerkingsTypeType
{
    Warehouse = 0,
    Crossdock = 1,
    Fastlane = 2,
    PickToLight = 3,
    PutToLight = 4,
    DropShip = 5,
    Montabot = 6,
    MontaShip = 7,
    Unknown = 8,
}
