// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ReturnForecast_ReturnForecast
{
    [JsonPropertyName("Code")] public string Code { get; set; } = default!;
    [JsonPropertyName("WebshopOrderId")] public string WebshopOrderId { get; set; } = default!;
    [JsonPropertyName("Lines")] public System.Collections.Generic.List<MontaRESTApiModels_ReturnForecast_ReturnForecastLine> Lines { get; set; } = default!;
    [JsonPropertyName("CauseDescription")] public string? CauseDescription { get; set; } = default!;
    [JsonPropertyName("Comment")] public string? Comment { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceCode")] public string? TrackAndTraceCode { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceLink")] public string? TrackAndTraceLink { get; set; } = default!;
    [JsonPropertyName("GeneralComment")] public string? GeneralComment { get; set; } = default!;
}
