// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Return_FollowedUpAction
{
    [JsonPropertyName("Code")] public string? Code { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
}
