// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ReturnForecast_ReturnForecastInvalidReasonsResponse
{
    [JsonPropertyName("ReturnForecastInvalidReasons")] public System.Collections.Generic.List<MontaRESTApiModels_ReturnForecast_ReturnForecastInvalidReason>? ReturnForecastInvalidReasons { get; set; } = default!;
}
