// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Dto_OrderDto
{
    [JsonPropertyName("Order")] public MontaRESTApiModels_Orders_Order? Order { get; set; } = default!;
}
