// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Product_ProductInvalidReasonsResponse
{
    [JsonPropertyName("ProductInvalidReasons")] public System.Collections.Generic.List<MontaRESTApiModels_Product_ProductInvalidReason>? ProductInvalidReasons { get; set; } = default!;
}
