// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
[JsonConverter(typeof(JsonStringEnumConverter))]
internal enum MontaRestApiModels_Orders_ReadUpdatedSinceStatusEnum
{
    NonDeleted = 0,
    Deleted = 1,
}
