// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_InboundForecastGroupInvalidReasonsResponse
{
    [JsonPropertyName("InboundForecastGroupInvalidReasons")] public System.Collections.Generic.List<MontaRESTApiModels_InboundForecast_InboundForecastGroupInvalidReason>? InboundForecastGroupInvalidReasons { get; set; } = default!;
}
