// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_Timeframe
{
    [JsonPropertyName("From")] public System.DateTimeOffset? From { get; set; } = default!;
    [JsonPropertyName("To")] public System.DateTimeOffset? To { get; set; } = default!;
    [JsonPropertyName("Recommended")] public bool? Recommended { get; set; } = default!;
    [JsonPropertyName("TypeCode")] public string? TypeCode { get; set; } = default!;
    [JsonPropertyName("IsSameDayDelivery")] public bool? IsSameDayDelivery { get; set; } = default!;
    [JsonPropertyName("TypeDescription")] public string? TypeDescription { get; set; } = default!;
    [JsonPropertyName("FromToTypeCode")] public string? FromToTypeCode { get; set; } = default!;
    [JsonPropertyName("ShippingOptions")] public System.Collections.Generic.List<MontaRESTApiModels_ShippingOptions_IndexResponseShippingOption>? ShippingOptions { get; set; } = default!;
    [JsonPropertyName("PickupPointDetails")] public MontaRESTApiModels_ShippingOptions_PickupPointDetails? PickupPointDetails { get; set; } = default!;
    [JsonPropertyName("IsPickupPoint")] public bool? IsPickupPoint { get; set; } = default!;
}
