// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Orders_ShippedOrder_ShippedOrder
{
    [JsonPropertyName("TotalWeightInKg")] public int? TotalWeightInKg { get; set; } = default!;
    [JsonPropertyName("PalletsShipped")] public int? PalletsShipped { get; set; } = default!;
    [JsonPropertyName("BoxesShipped")] public int? BoxesShipped { get; set; } = default!;
    [JsonPropertyName("ShippedPallets")] public System.Text.Json.Nodes.JsonObject? ShippedPallets { get; set; } = default!;
    [JsonPropertyName("ShippedBoxesOnPallets")] public System.Collections.Generic.List<MontaRestApiModels_Orders_ShippedOrder_RecordDto_ShippedBox>? ShippedBoxesOnPallets { get; set; } = default!;
    [JsonPropertyName("ShippedBoxesNotOnPallets")] public System.Collections.Generic.List<MontaRestApiModels_Orders_ShippedOrder_RecordDto_ShippedBox>? ShippedBoxesNotOnPallets { get; set; } = default!;
}
