// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Return_LineToUpdateStatusOf
{
    [JsonPropertyName("LineId")] public int? LineId { get; set; } = default!;
    [JsonPropertyName("Status")] public string? Status { get; set; } = default!;
}
