// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Orders_ShippedOrder_RecordDto_ShippedBox
{
    [JsonPropertyName("DistinctProducts")] public int? DistinctProducts { get; set; } = default!;
    [JsonPropertyName("TotalProducts")] public int? TotalProducts { get; set; } = default!;
    [JsonPropertyName("ShippedCarrierInfo")] public MontaRestApiModels_Orders_ShippedOrder_RecordDto_ShippedCarrierInfo? ShippedCarrierInfo { get; set; } = default!;
    [JsonPropertyName("ShippedProduct")] public System.Collections.Generic.List<MontaRestApiModels_Orders_ShippedOrder_RecordDto_ShippedProduct>? ShippedProduct { get; set; } = default!;
}
