// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_IndexResponse
{
    [JsonPropertyName("Warnings")] public System.Collections.Generic.List<MontaRESTApiModels_ShippingOptions_MessageWithShipperCode>? Warnings { get; set; } = default!;
    [JsonPropertyName("Timeframes")] public System.Collections.Generic.List<MontaRESTApiModels_ShippingOptions_Timeframe>? Timeframes { get; set; } = default!;
    [JsonPropertyName("ImpossibleShipperOptions")] public System.Collections.Generic.List<MontaRESTApiModels_ShippingOptions_ImpossibleShipperOption>? ImpossibleShipperOptions { get; set; } = default!;
    [JsonPropertyName("Notices")] public System.Collections.Generic.List<MontaRESTApiModels_ShippingOptions_MessageWithShipperCode>? Notices { get; set; } = default!;
}
