// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
[JsonConverter(typeof(JsonStringEnumConverter))]
internal enum MontaModel_Efulfillment_Eorders_EorderHeader_MontapackerReason
{
    Suitable = 0,
    TooBig = 1,
    CustomerTurnedOff = 2,
    OrderSizeNotSuitable = 3,
    WarehouseWithoutMontapacker = 4,
    PickStatusNotWarehouse = 5,
    OrdersOfChannelNotAllowed = 6,
    ShipperNotAllowed = 7,
    SurprisePack = 8,
    OrderNotSuitableEcheckwall = 9,
    OrderNotSuitablePutl = 10,
    OrderTooHeavy = 11,
    OrderShippedInOwnPacking = 12,
    OrderContainsFragileProducts = 13,
    OrderContainsNotSuitableProducts = 14,
    ProductsWithMissingDimensions = 15,
    OrderContainsTooManyItems = 16,
    OrderIsBuspost = 17,
    ProFormaOrder = 18,
    CalculationError = 19,
    OrderIsTooSmall = 20,
}
