// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Info_Info
{
    [JsonPropertyName("Origins")] public System.Collections.Generic.List<MontaRESTApiModels_Info_Origin>? Origins { get; set; } = default!;
    [JsonPropertyName("Warehouses")] public System.Collections.Generic.List<MontaRESTApiModels_Info_Warehouse>? Warehouses { get; set; } = default!;
}
