// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Supplier_UpdateSupplier
{
    [JsonPropertyName("Code")] public string Code { get; set; } = default!;
    [JsonPropertyName("Title")] public string? Title { get; set; } = default!;
    [JsonPropertyName("AddressName")] public string? AddressName { get; set; } = default!;
    [JsonPropertyName("AddressStreet")] public string? AddressStreet { get; set; } = default!;
    [JsonPropertyName("AddressHouseNo")] public string? AddressHouseNo { get; set; } = default!;
    [JsonPropertyName("AddressHouseNoAddition")] public string? AddressHouseNoAddition { get; set; } = default!;
    [JsonPropertyName("AddressPostalCode")] public string? AddressPostalCode { get; set; } = default!;
    [JsonPropertyName("AddressCity")] public string? AddressCity { get; set; } = default!;
    [JsonPropertyName("AddressState")] public string? AddressState { get; set; } = default!;
    [JsonPropertyName("AddressCountry")] public string? AddressCountry { get; set; } = default!;
    [JsonPropertyName("AddressPhone")] public string? AddressPhone { get; set; } = default!;
    [JsonPropertyName("AddressEmail")] public string? AddressEmail { get; set; } = default!;
    [JsonPropertyName("CreditorNumber")] public string? CreditorNumber { get; set; } = default!;
    [JsonPropertyName("Default")] public bool? Default { get; set; } = default!;
}
