// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModel_Efulfillment_Eorders_DeliveryInformation
{
    [JsonPropertyName("MateriaalId")] public int? MateriaalId { get; set; } = default!;
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("ProductDescription")] public string? ProductDescription { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
    [JsonPropertyName("ExpectedDeliveryDate")] public System.DateTimeOffset? ExpectedDeliveryDate { get; set; } = default!;
    [JsonPropertyName("InboundForecastGroupId")] public int? InboundForecastGroupId { get; set; } = default!;
    [JsonPropertyName("InboundForecastGroupReference")] public string? InboundForecastGroupReference { get; set; } = default!;
    [JsonPropertyName("PossiblyAvailableInboundForecasts")] public System.Collections.Generic.List<MontaModel_Efulfillment_Eorders_ForecastedProduct>? PossiblyAvailableInboundForecasts { get; set; } = default!;
    [JsonPropertyName("ReservedForecastedInbounds")] public System.Collections.Generic.List<MontaModel_Efulfillment_Eorders_ForecastedProduct>? ReservedForecastedInbounds { get; set; } = default!;
}
