// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_OrderShipperOption
{
    [JsonPropertyName("ShipperCode")] public string ShipperCode { get; set; } = default!;
    [JsonPropertyName("Code")] public string Code { get; set; } = default!;
    [JsonPropertyName("Value")] public string? Value { get; set; } = default!;
}
