// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Orders_SplitOrders_SplitResult
{
    [JsonPropertyName("OriginalOrder")] public MontaRESTApiModels_Orders_Order? OriginalOrder { get; set; } = default!;
    [JsonPropertyName("NewOrder")] public MontaRESTApiModels_Orders_Order? NewOrder { get; set; } = default!;
}
