// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_IndexParameters
{
    [JsonPropertyName("Origin")] public string Origin { get; set; } = default!;
    [JsonPropertyName("OrderValueInclVat")] public double? OrderValueInclVat { get; set; } = default!;
    [JsonPropertyName("Currency")] public string Currency { get; set; } = default!;
    [JsonPropertyName("Language")] public string Language { get; set; } = default!;
    [JsonPropertyName("Address")] public MontaRESTApiModels_ShippingOptions_Address Address { get; set; } = default!;
    [JsonPropertyName("AllowedShippers")] public System.Collections.Generic.List<string>? AllowedShippers { get; set; } = default!;
    [JsonPropertyName("Ordered")] public System.DateTimeOffset? Ordered { get; set; } = default!;
    [JsonPropertyName("ProductsOnStock")] public bool? ProductsOnStock { get; set; } = default!;
    [JsonPropertyName("MaxNumberOfPickupPoints")] public int? MaxNumberOfPickupPoints { get; set; } = default!;
    [JsonPropertyName("Products")] public System.Collections.Generic.List<MontaRESTApiModels_ShippingOptions_CheckOutProduct>? Products { get; set; } = default!;
    [JsonPropertyName("NoTimeout")] public bool? NoTimeout { get; set; } = default!;
    [JsonPropertyName("OnlyPickupPoints")] public bool? OnlyPickupPoints { get; set; } = default!;
    [JsonPropertyName("HideDHLPackStations")] public bool? HideDHLPackStations { get; set; } = default!;
    [JsonPropertyName("SystemInfo")] public MontaRestApiModels_ShippingOptions_SystemInfo? SystemInfo { get; set; } = default!;
}
