// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Product_StockForWarehouse
{
    [JsonPropertyName("Warehouse")] public MontaRESTApiModels_Info_Warehouse? Warehouse { get; set; } = default!;
    [JsonPropertyName("StockQuarantaine")] public int? StockQuarantaine { get; set; } = default!;
    [JsonPropertyName("StockAll")] public int? StockAll { get; set; } = default!;
    [JsonPropertyName("StockBlocked")] public int? StockBlocked { get; set; } = default!;
    [JsonPropertyName("StockInTransit")] public int? StockInTransit { get; set; } = default!;
    [JsonPropertyName("StockReserved")] public int? StockReserved { get; set; } = default!;
    [JsonPropertyName("StockAvailable")] public int? StockAvailable { get; set; } = default!;
    [JsonPropertyName("StockSplitProduct")] public int? StockSplitProduct { get; set; } = default!;
    [JsonPropertyName("StockOpen")] public int? StockOpen { get; set; } = default!;
    [JsonPropertyName("MaxPhysicalStock")] public int? MaxPhysicalStock { get; set; } = default!;
    [JsonPropertyName("MinPhysicalStock")] public int? MinPhysicalStock { get; set; } = default!;
}
