// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Pickroutes_PickRouteDto
{
    [JsonPropertyName("WithPickingAction")] public int? WithPickingAction { get; set; } = default!;
    [JsonPropertyName("AssignedMin")] public System.DateTimeOffset? AssignedMin { get; set; } = default!;
    [JsonPropertyName("EorderWebshopOrderID")] public string? EorderWebshopOrderID { get; set; } = default!;
    [JsonPropertyName("Code")] public string? Code { get; set; } = default!;
    [JsonPropertyName("WarehouseDisplayName")] public string? WarehouseDisplayName { get; set; } = default!;
    [JsonPropertyName("ProductIdCustomer")] public string? ProductIdCustomer { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
    [JsonPropertyName("Amount")] public int? Amount { get; set; } = default!;
    [JsonPropertyName("Picked")] public System.DateTimeOffset? Picked { get; set; } = default!;
}
