// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_ImpossibleShipperOptionReason
{
    [JsonPropertyName("Code")] public string? Code { get; set; } = default!;
    [JsonPropertyName("Reason")] public string? Reason { get; set; } = default!;
}
