// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_Collo
{
    [JsonPropertyName("Number")] public int Number { get; set; } = default!;
    [JsonPropertyName("WeightGrammes")] public int? WeightGrammes { get; set; } = default!;
    [JsonPropertyName("LengthMm")] public int? LengthMm { get; set; } = default!;
    [JsonPropertyName("WidthMm")] public int? WidthMm { get; set; } = default!;
    [JsonPropertyName("HeightMm")] public int? HeightMm { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceCode")] public string? TrackAndTraceCode { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceLink")] public string? TrackAndTraceLink { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusDescription")] public string? DeliveryStatusDescription { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusCode")] public string? DeliveryStatusCode { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusUpdated")] public System.DateTimeOffset? DeliveryStatusUpdated { get; set; } = default!;
    [JsonPropertyName("PackageDescription")] public string? PackageDescription { get; set; } = default!;
    [JsonPropertyName("IsParent")] public bool? IsParent { get; set; } = default!;
    [JsonPropertyName("ParentNumber")] public int? ParentNumber { get; set; } = default!;
    [JsonPropertyName("Products")] public System.Collections.Generic.List<MontaRESTApiModels_Orders_ColloProduct>? Products { get; set; } = default!;
}
