// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ReturnForecast_ReturnReason
{
    [JsonPropertyName("Id")] public int? Id { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
    [JsonPropertyName("Translations")] public System.Text.Json.Nodes.JsonObject? Translations { get; set; } = default!;
}
