// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Orders_ShippedOrder_RecordDto_ShippedCarrierInfo
{
    [JsonPropertyName("TTColloNr")] public int? TTColloNr { get; set; } = default!;
    [JsonPropertyName("PackageDescription")] public string? PackageDescription { get; set; } = default!;
    [JsonPropertyName("WeightInGrams")] public int? WeightInGrams { get; set; } = default!;
    [JsonPropertyName("LengthInMM")] public int? LengthInMM { get; set; } = default!;
    [JsonPropertyName("WidthInMM")] public int? WidthInMM { get; set; } = default!;
    [JsonPropertyName("HeightInMM")] public int? HeightInMM { get; set; } = default!;
    [JsonPropertyName("IsProductItsOwnPackage")] public bool? IsProductItsOwnPackage { get; set; } = default!;
    [JsonPropertyName("FitsThroughDutchMailBox")] public string? FitsThroughDutchMailBox { get; set; } = default!;
    [JsonPropertyName("TTCode")] public string? TTCode { get; set; } = default!;
    [JsonPropertyName("TTLink")] public string? TTLink { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusDescription")] public string? DeliveryStatusDescription { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusCode")] public string? DeliveryStatusCode { get; set; } = default!;
    [JsonPropertyName("DeliveryStatusUpdatedAt")] public string? DeliveryStatusUpdatedAt { get; set; } = default!;
}
