// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_OrderLine
{
    [JsonPropertyName("Sku")] public string Sku { get; set; } = default!;
    [JsonPropertyName("OrderedQuantity")] public int OrderedQuantity { get; set; } = default!;
    [JsonPropertyName("WebshopOrderLineId")] public string? WebshopOrderLineId { get; set; } = default!;
    [JsonPropertyName("Occured")] public System.DateTimeOffset? Occured { get; set; } = default!;
    [JsonPropertyName("IsFlyer")] public bool? IsFlyer { get; set; } = default!;
    [JsonPropertyName("Backorder")] public bool? Backorder { get; set; } = default!;
    [JsonPropertyName("HasBeenBackorder")] public bool? HasBeenBackorder { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
    [JsonPropertyName("ShippingLabels")] public System.Collections.Generic.List<MontaRESTApiModels_Orders_OrderShippingLabels>? ShippingLabels { get; set; } = default!;
    [JsonPropertyName("BatchCode")] public string? BatchCode { get; set; } = default!;
    [JsonPropertyName("Guid")] public string? Guid { get; set; } = default!;
    [JsonPropertyName("RegisterSerialNumber")] public bool? RegisterSerialNumber { get; set; } = default!;
    [JsonPropertyName("OriginalOrderNumber")] public string? OriginalOrderNumber { get; set; } = default!;
}
