// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_DefferedDeliveryOption
{
    [JsonPropertyName("OrderShipmentDays")] public int? OrderShipmentDays { get; set; } = default!;
    [JsonPropertyName("Discount")] public double? Discount { get; set; } = default!;
}
