// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Orders_ShippedOrder_RecordDto_ShippedPallet
{
    [JsonPropertyName("TrackAndTraceInfo")] public MontaRestApiModels_Orders_ShippedOrder_RecordDto_ShippedCarrierInfo? TrackAndTraceInfo { get; set; } = default!;
    [JsonPropertyName("ShippedBoxes")] public System.Collections.Generic.List<MontaRestApiModels_Orders_ShippedOrder_RecordDto_ShippedBox>? ShippedBoxes { get; set; } = default!;
}
