// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Orders_ShippedOrder_RecordDto_ShippedProduct
{
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("Quantity")] public int? Quantity { get; set; } = default!;
    [JsonPropertyName("Lenght")] public int? Lenght { get; set; } = default!;
    [JsonPropertyName("Width")] public int? Width { get; set; } = default!;
    [JsonPropertyName("Height")] public int? Height { get; set; } = default!;
    [JsonPropertyName("Weight")] public int? Weight { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
}
