// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_ColloProduct
{
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("Quantity")] public int? Quantity { get; set; } = default!;
}
