// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_ShippingLabel
{
    [JsonPropertyName("FileName")] public string? FileName { get; set; } = default!;
    [JsonPropertyName("Colli")] public System.Collections.Generic.List<MontaRESTApiModels_Orders_Collo>? Colli { get; set; } = default!;
}
