// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_OrderShippingLabels
{
    [JsonPropertyName("FileName")] public string FileName { get; set; } = default!;
    [JsonPropertyName("Base64FileContent")] public string Base64FileContent { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceLink")] public string? TrackAndTraceLink { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceCode")] public string? TrackAndTraceCode { get; set; } = default!;
}
