// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_OrderDeliveryInformation
{
    [JsonPropertyName("ExpectedProcessingDate")] public System.DateTimeOffset? ExpectedProcessingDate { get; set; } = default!;
    [JsonPropertyName("DeliveryInformation")] public System.Collections.Generic.List<MontaModel_Efulfillment_Eorders_DeliveryInformation>? DeliveryInformation { get; set; } = default!;
}
