// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModel_WMS_Materialen_ProductGroups_Models_ProductGroup
{
    [JsonPropertyName("Id")] public int? Id { get; set; } = default!;
    [JsonPropertyName("GroupName")] public string? GroupName { get; set; } = default!;
    [JsonPropertyName("RelatieID")] public int? RelatieID { get; set; } = default!;
    [JsonPropertyName("RelatieSystemConnectionId")] public int? RelatieSystemConnectionId { get; set; } = default!;
    [JsonPropertyName("BlockedInRma")] public bool? BlockedInRma { get; set; } = default!;
    [JsonPropertyName("CommentRequired")] public bool? CommentRequired { get; set; } = default!;
    [JsonPropertyName("IdsOfProducts")] public System.Collections.Generic.List<int>? IdsOfProducts { get; set; } = default!;
    [JsonPropertyName("CustomBlockedDescription")] public string? CustomBlockedDescription { get; set; } = default!;
    [JsonPropertyName("BlockedDescriptionTranslations")] public System.Collections.Generic.List<MontaModel_WMS_Materialen_ProductGroups_Models_ProductGroupBlockedDescriptionTranslation>? BlockedDescriptionTranslations { get; set; } = default!;
    [JsonPropertyName("UsedForTradeIn")] public bool? UsedForTradeIn { get; set; } = default!;
}
