// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Dto_ProductsDto
{
    [JsonPropertyName("Products")] public System.Collections.Generic.List<MontaRestApiModels_Dto_ProductDto>? Products { get; set; } = default!;
}
