// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Return_SerialNo
{
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("SerialNumber")] public string? SerialNumber { get; set; } = default!;
    [JsonPropertyName("Aanmaakdatum")] public System.DateTimeOffset? Aanmaakdatum { get; set; } = default!;
}
