// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Supplier_SupplierInvalidReasonResponse
{
    [JsonPropertyName("SupplierInvalidReasons")] public System.Collections.Generic.List<MontaRESTApiModels_Supplier_SupplierInvalidReason>? SupplierInvalidReasons { get; set; } = default!;
}
