// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Reports_Report
{
    [JsonPropertyName("Id")] public string? Id { get; set; } = default!;
    [JsonPropertyName("ReportName")] public string? ReportName { get; set; } = default!;
    [JsonPropertyName("Downloaded")] public bool? Downloaded { get; set; } = default!;
    [JsonPropertyName("CreatedAt")] public System.DateTimeOffset? CreatedAt { get; set; } = default!;
}
