// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_IndexResponseShippingOption
{
    [JsonPropertyName("Code")] public string? Code { get; set; } = default!;
    [JsonPropertyName("ShipperCodes")] public System.Collections.Generic.List<string>? ShipperCodes { get; set; } = default!;
    [JsonPropertyName("ShipperOptionCodes")] public System.Collections.Generic.List<string>? ShipperOptionCodes { get; set; } = default!;
    [JsonPropertyName("ShipperOptionsWithValue")] public System.Text.Json.Nodes.JsonObject? ShipperOptionsWithValue { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
    [JsonPropertyName("DisplayName")] public string? DisplayName { get; set; } = default!;
    [JsonPropertyName("IsMailbox")] public bool? IsMailbox { get; set; } = default!;
    [JsonPropertyName("SellPrice")] public double? SellPrice { get; set; } = default!;
    [JsonPropertyName("SellPriceWithoutDiscount")] public double? SellPriceWithoutDiscount { get; set; } = default!;
    [JsonPropertyName("SellPriceCurrency")] public string? SellPriceCurrency { get; set; } = default!;
    [JsonPropertyName("VATRate")] public double? VATRate { get; set; } = default!;
    [JsonPropertyName("From")] public System.DateTimeOffset? From { get; set; } = default!;
    [JsonPropertyName("To")] public System.DateTimeOffset? To { get; set; } = default!;
    [JsonPropertyName("IsPreferred")] public bool? IsPreferred { get; set; } = default!;
    [JsonPropertyName("IsSustainable")] public bool? IsSustainable { get; set; } = default!;
    [JsonPropertyName("DiscountPercentage")] public int? DiscountPercentage { get; set; } = default!;
    [JsonPropertyName("DefferedDeliveryOption")] public MontaRESTApiModels_ShippingOptions_DefferedDeliveryOption? DefferedDeliveryOption { get; set; } = default!;
    [JsonPropertyName("ImageUrl")] public string? ImageUrl { get; set; } = default!;
    [JsonPropertyName("HideDeliveryPromise")] public bool? HideDeliveryPromise { get; set; } = default!;
    [JsonPropertyName("SortDate")] public System.DateTimeOffset? SortDate { get; set; } = default!;
    [JsonPropertyName("Recommended")] public bool? Recommended { get; set; } = default!;
    [JsonPropertyName("Options")] public System.Collections.Generic.List<MontaRESTApiModels_ShippingOptions_IndexResponseShippingOptionOption>? Options { get; set; } = default!;
    [JsonPropertyName("ShippingDeadline")] public System.DateTimeOffset? ShippingDeadline { get; set; } = default!;
    [JsonPropertyName("IsEveningDelivery")] public bool? IsEveningDelivery { get; set; } = default!;
    [JsonPropertyName("IsSaturdayDelivery")] public bool? IsSaturdayDelivery { get; set; } = default!;
    [JsonPropertyName("IsSamedayDelivery")] public bool? IsSamedayDelivery { get; set; } = default!;
    [JsonPropertyName("TypeCode")] public string? TypeCode { get; set; } = default!;
    [JsonPropertyName("TypeDescription")] public string? TypeDescription { get; set; } = default!;
    [JsonPropertyName("FromToTypeCode")] public string? FromToTypeCode { get; set; } = default!;
}
