// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Product_StockForLocation
{
    [JsonPropertyName("LocationId")] public int? LocationId { get; set; } = default!;
    [JsonPropertyName("LocationCode")] public string? LocationCode { get; set; } = default!;
    [JsonPropertyName("WarehouseId")] public int? WarehouseId { get; set; } = default!;
    [JsonPropertyName("StockAll")] public int? StockAll { get; set; } = default!;
    [JsonPropertyName("StockQuarantaine")] public int? StockQuarantaine { get; set; } = default!;
    [JsonPropertyName("StockBlocked")] public int? StockBlocked { get; set; } = default!;
    [JsonPropertyName("StockInTransit")] public int? StockInTransit { get; set; } = default!;
    [JsonPropertyName("StockInPicking")] public int? StockInPicking { get; set; } = default!;
    [JsonPropertyName("MaxPhysicalStock")] public int? MaxPhysicalStock { get; set; } = default!;
    [JsonPropertyName("MinPhysicalStock")] public int? MinPhysicalStock { get; set; } = default!;
}
