// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_PurchaseOrderGroup
{
    [JsonPropertyName("ID")] public int? ID { get; set; } = default!;
    [JsonPropertyName("Comment")] public string? Comment { get; set; } = default!;
    [JsonPropertyName("InboundForecastGroupID")] public int? InboundForecastGroupID { get; set; } = default!;
    [JsonPropertyName("SupplierID")] public int? SupplierID { get; set; } = default!;
    [JsonPropertyName("Reference")] public string? Reference { get; set; } = default!;
    [JsonPropertyName("ExpectedDeliveryDate")] public System.DateTimeOffset? ExpectedDeliveryDate { get; set; } = default!;
    [JsonPropertyName("TTLink")] public string? TTLink { get; set; } = default!;
    [JsonPropertyName("Lines")] public System.Collections.Generic.List<MontaRESTApiModels_Orders_PurchaseOrder>? Lines { get; set; } = default!;
}
