// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModelShippers_Generic_Pickup_PickupPointOpeningTimes
{
    [JsonPropertyName("Day")] public string? Day { get; set; } = default!;
    [JsonPropertyName("OpeningTimes")] public System.Collections.Generic.List<MontaModelShippers_Generic_Pickup_OpeningTimes>? OpeningTimes { get; set; } = default!;
}
