// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModel_WMS_Batches_Batch
{
    [JsonPropertyName("Id")] public int? Id { get; set; } = default!;
    [JsonPropertyName("Title")] public string? Title { get; set; } = default!;
    [JsonPropertyName("BestBefore")] public System.DateTimeOffset? BestBefore { get; set; } = default!;
    [JsonPropertyName("MateriaalId")] public int? MateriaalId { get; set; } = default!;
    [JsonPropertyName("Active")] public bool? Active { get; set; } = default!;
    [JsonPropertyName("SupplierId")] public int? SupplierId { get; set; } = default!;
    [JsonPropertyName("BatchGuid")] public string? BatchGuid { get; set; } = default!;
}
