// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Return_ReturnDocument
{
    [JsonPropertyName("ReturnId")] public int? ReturnId { get; set; } = default!;
    [JsonPropertyName("Type")] public string? Type { get; set; } = default!;
    [JsonPropertyName("TypeId")] public int? TypeId { get; set; } = default!;
    [JsonPropertyName("EncodedData")] public string? EncodedData { get; set; } = default!;
    [JsonPropertyName("FileExtension")] public string? FileExtension { get; set; } = default!;
}
