// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Batches_Batch
{
    [JsonPropertyName("Reference")] public string? Reference { get; set; } = default!;
    [JsonPropertyName("Quantity")] public int? Quantity { get; set; } = default!;
    [JsonPropertyName("BestBeforeDate")] public System.DateTimeOffset? BestBeforeDate { get; set; } = default!;
    [JsonPropertyName("StockAll")] public int? StockAll { get; set; } = default!;
    [JsonPropertyName("StockQuarantaine")] public int? StockQuarantaine { get; set; } = default!;
    [JsonPropertyName("StockBlocked")] public int? StockBlocked { get; set; } = default!;
    [JsonPropertyName("StockInTransit")] public int? StockInTransit { get; set; } = default!;
    [JsonPropertyName("StockReserved")] public int? StockReserved { get; set; } = default!;
    [JsonPropertyName("StockAvailble")] public int? StockAvailble { get; set; } = default!;
    [JsonPropertyName("StockInWarehouse")] public int? StockInWarehouse { get; set; } = default!;
}
