// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
[JsonConverter(typeof(JsonStringEnumConverter))]
internal enum MontaModel_Efulfillment_Eorders_EorderHeader_BackorderHandlingType
{
    Default = 0,
    AutoSplit = 1,
    NoBackorders = 2,
}
