// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModelInterfaces_IContactDetails
{
    [JsonPropertyName("City")] public string? City { get; set; } = default!;
    [JsonPropertyName("Company")] public string? Company { get; set; } = default!;
    [JsonPropertyName("Country")] public string? Country { get; set; } = default!;
    [JsonPropertyName("DisplayName")] public string? DisplayName { get; set; } = default!;
    [JsonPropertyName("Email")] public string? Email { get; set; } = default!;
    [JsonPropertyName("EorderId")] public int? EorderId { get; set; } = default!;
    [JsonPropertyName("FirstName")] public string? FirstName { get; set; } = default!;
    [JsonPropertyName("FirstNameMiddleName")] public string? FirstNameMiddleName { get; set; } = default!;
    [JsonPropertyName("FullAddress")] public string? FullAddress { get; set; } = default!;
    [JsonPropertyName("FullAddress2")] public string? FullAddress2 { get; set; } = default!;
    [JsonPropertyName("FullName")] public string? FullName { get; set; } = default!;
    [JsonPropertyName("FullNameOrCompany")] public string? FullNameOrCompany { get; set; } = default!;
    [JsonPropertyName("HasStreet")] public bool? HasStreet { get; set; } = default!;
    [JsonPropertyName("HouseNo")] public string? HouseNo { get; set; } = default!;
    [JsonPropertyName("HouseNoAddition")] public string? HouseNoAddition { get; set; } = default!;
    [JsonPropertyName("IsEmpty")] public bool? IsEmpty { get; set; } = default!;
    [JsonPropertyName("IsPostbus")] public bool? IsPostbus { get; set; } = default!;
    [JsonPropertyName("IsWaddeneiland")] public bool? IsWaddeneiland { get; set; } = default!;
    [JsonPropertyName("LastName")] public string? LastName { get; set; } = default!;
    [JsonPropertyName("MiddleLastName")] public string? MiddleLastName { get; set; } = default!;
    [JsonPropertyName("MiddleName")] public string? MiddleName { get; set; } = default!;
    [JsonPropertyName("Phone")] public string? Phone { get; set; } = default!;
    [JsonPropertyName("PostalCode")] public string? PostalCode { get; set; } = default!;
    [JsonPropertyName("State")] public string? State { get; set; } = default!;
    [JsonPropertyName("Street")] public string? Street { get; set; } = default!;
}
