// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_ShippingOptions_SystemInfo
{
    [JsonPropertyName("ID")] public int? ID { get; set; } = default!;
    [JsonPropertyName("EsettingID")] public int? EsettingID { get; set; } = default!;
    [JsonPropertyName("CoreSoftware")] public string? CoreSoftware { get; set; } = default!;
    [JsonPropertyName("CoreVersion")] public string? CoreVersion { get; set; } = default!;
    [JsonPropertyName("CheckoutApiWrapperVersion")] public string? CheckoutApiWrapperVersion { get; set; } = default!;
    [JsonPropertyName("ModuleName")] public string? ModuleName { get; set; } = default!;
    [JsonPropertyName("ModuleVersion")] public string? ModuleVersion { get; set; } = default!;
    [JsonPropertyName("PhpVersion")] public string? PhpVersion { get; set; } = default!;
    [JsonPropertyName("OperatingSystem")] public string? OperatingSystem { get; set; } = default!;
    [JsonPropertyName("ModifiedAt")] public System.DateTimeOffset? ModifiedAt { get; set; } = default!;
}
