// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Inbounds_Inbound
{
    [JsonPropertyName("Id")] public int? Id { get; set; } = default!;
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("Quantity")] public int? Quantity { get; set; } = default!;
    [JsonPropertyName("Created")] public System.DateTimeOffset? Created { get; set; } = default!;
    [JsonPropertyName("Type")] public string? Type { get; set; } = default!;
    [JsonPropertyName("Quarantaine")] public bool? Quarantaine { get; set; } = default!;
    [JsonPropertyName("ReturnedOrderWebshopOrderId")] public string? ReturnedOrderWebshopOrderId { get; set; } = default!;
    [JsonPropertyName("Reference")] public string? Reference { get; set; } = default!;
    [JsonPropertyName("InboundForecastReference")] public string? InboundForecastReference { get; set; } = default!;
    [JsonPropertyName("InboundForecastSupplier")] public MontaRESTApiModels_Supplier_Supplier? InboundForecastSupplier { get; set; } = default!;
    [JsonPropertyName("InboundReference")] public string? InboundReference { get; set; } = default!;
    [JsonPropertyName("InboundSupplier")] public MontaRESTApiModels_Supplier_Supplier? InboundSupplier { get; set; } = default!;
    [JsonPropertyName("Batch")] public MontaRESTApiModels_Batches_Batch? Batch { get; set; } = default!;
    [JsonPropertyName("InboundForecastComment")] public string? InboundForecastComment { get; set; } = default!;
    [JsonPropertyName("WarehouseDisplayName")] public string? WarehouseDisplayName { get; set; } = default!;
}
