// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_InboundForecast_UpdateInboundForecast
{
    [JsonPropertyName("DeliveryDate")] public System.DateTimeOffset? DeliveryDate { get; set; } = default!;
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("Quantity")] public int Quantity { get; set; } = default!;
    [JsonPropertyName("Approved")] public bool? Approved { get; set; } = default!;
    [JsonPropertyName("QuantityReceived")] public int? QuantityReceived { get; set; } = default!;
    [JsonPropertyName("Reference")] public string? Reference { get; set; } = default!;
    [JsonPropertyName("Comment")] public string? Comment { get; set; } = default!;
    [JsonPropertyName("Batch")] public string? Batch { get; set; } = default!;
    [JsonPropertyName("BatchTHT")] public System.DateTimeOffset? BatchTHT { get; set; } = default!;
    [JsonPropertyName("InboundForecastId")] public int? InboundForecastId { get; set; } = default!;
    [JsonPropertyName("ExpectedDeliveryDate")] public System.DateTimeOffset? ExpectedDeliveryDate { get; set; } = default!;
    [JsonPropertyName("ReceivedDates")] public System.Collections.Generic.List<System.DateTimeOffset>? ReceivedDates { get; set; } = default!;
}
