// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModel_Efulfillment_Returns_Forecasts_Forecast
{
    [JsonPropertyName("_lines")] public System.Collections.Generic.List<MontaModel_Efulfillment_Returns_Forecasts_Line>? Lines { get; set; } = default!;
    [JsonPropertyName("Id")] public int? Id { get; set; } = default!;
    [JsonPropertyName("EorderId")] public int? EorderId { get; set; } = default!;
    [JsonPropertyName("ViaServicePointId")] public int? ViaServicePointId { get; set; } = default!;
    [JsonPropertyName("RmaOrderId")] public int? RmaOrderId { get; set; } = default!;
    [JsonPropertyName("Lines")] public System.Collections.Generic.List<MontaModel_Efulfillment_Returns_Forecasts_Line>? Lines2 { get; set; } = default!;
    [JsonPropertyName("Comment")] public string? Comment { get; set; } = default!;
    [JsonPropertyName("CommentConsumer")] public string? CommentConsumer { get; set; } = default!;
    [JsonPropertyName("Code")] public string? Code { get; set; } = default!;
    [JsonPropertyName("RelatieId")] public int? RelatieId { get; set; } = default!;
    [JsonPropertyName("CauseDescriptionConsumer")] public string? CauseDescriptionConsumer { get; set; } = default!;
    [JsonPropertyName("Created")] public System.DateTimeOffset? Created { get; set; } = default!;
    [JsonPropertyName("ReturnId")] public int? ReturnId { get; set; } = default!;
    [JsonPropertyName("IsEnRoute")] public bool? IsEnRoute { get; set; } = default!;
    [JsonPropertyName("IsDelivered")] public bool? IsDelivered { get; set; } = default!;
    [JsonPropertyName("IsDeliveredUnknown")] public bool? IsDeliveredUnknown { get; set; } = default!;
    [JsonPropertyName("CreationSystemId")] public int? CreationSystemId { get; set; } = default!;
    [JsonPropertyName("ShipperId")] public int? ShipperId { get; set; } = default!;
    [JsonPropertyName("PickupDate")] public System.DateTimeOffset? PickupDate { get; set; } = default!;
    [JsonPropertyName("AmountOfPackages")] public int? AmountOfPackages { get; set; } = default!;
    [JsonPropertyName("Completed")] public bool? Completed { get; set; } = default!;
    [JsonPropertyName("TradeInEorderId")] public int? TradeInEorderId { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceCode")] public string? TrackAndTraceCode { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceLink")] public string? TrackAndTraceLink { get; set; } = default!;
    [JsonPropertyName("RmaSettingsId")] public int? RmaSettingsId { get; set; } = default!;
}
