// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_IndexResponseShippingOptionOption
{
    [JsonPropertyName("Code")] public string? Code { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
    [JsonPropertyName("SellPrice")] public double? SellPrice { get; set; } = default!;
    [JsonPropertyName("SellPriceCurrency")] public string? SellPriceCurrency { get; set; } = default!;
    [JsonPropertyName("VATRate")] public double? VATRate { get; set; } = default!;
}
