// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Info_Warehouse
{
    [JsonPropertyName("Guid")] public string? Guid { get; set; } = default!;
    [JsonPropertyName("Name")] public string? Name { get; set; } = default!;
    [JsonPropertyName("OwnedByYou")] public bool? OwnedByYou { get; set; } = default!;
}
