// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_Event
{
    [JsonPropertyName("Id")] public int? Id { get; set; } = default!;
    [JsonPropertyName("WebshopOrderId")] public string? WebshopOrderId { get; set; } = default!;
    [JsonPropertyName("TypeCode")] public string? TypeCode { get; set; } = default!;
    [JsonPropertyName("TypeId")] public int? TypeId { get; set; } = default!;
    [JsonPropertyName("Description")] public string? Description { get; set; } = default!;
    [JsonPropertyName("Occured")] public System.DateTimeOffset? Occured { get; set; } = default!;
    [JsonPropertyName("Created")] public System.DateTimeOffset? Created { get; set; } = default!;
    [JsonPropertyName("EorderID")] public int? EorderID { get; set; } = default!;
}
