// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ReturnForecast_ReturnLabel
{
    [JsonPropertyName("EncodedData")] public string? EncodedData { get; set; } = default!;
    [JsonPropertyName("FileExtension")] public string? FileExtension { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceLink")] public string? TrackAndTraceLink { get; set; } = default!;
    [JsonPropertyName("TrackAndTraceCode")] public string? TrackAndTraceCode { get; set; } = default!;
}
