// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_RmaLogin
{
    [JsonPropertyName("Url")] public string? Url { get; set; } = default!;
    [JsonPropertyName("ValidUntil")] public System.DateTimeOffset? ValidUntil { get; set; } = default!;
    [JsonPropertyName("IsWarranty")] public bool? IsWarranty { get; set; } = default!;
    [JsonPropertyName("IsFree")] public bool? IsFree { get; set; } = default!;
    [JsonPropertyName("Guid")] public string? Guid { get; set; } = default!;
}
