// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_Address
{
    [JsonPropertyName("Street")] public string? Street { get; set; } = default!;
    [JsonPropertyName("HouseNumber")] public string? HouseNumber { get; set; } = default!;
    [JsonPropertyName("HouseNumberAddition")] public string? HouseNumberAddition { get; set; } = default!;
    [JsonPropertyName("PostalCode")] public string? PostalCode { get; set; } = default!;
    [JsonPropertyName("City")] public string? City { get; set; } = default!;
    [JsonPropertyName("State")] public string? State { get; set; } = default!;
    [JsonPropertyName("CountryCode")] public string CountryCode { get; set; } = default!;
}
