// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_InboundForecast_InboundForecastEvent
{
    [JsonPropertyName("EventId")] public int? EventId { get; set; } = default!;
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("EventCode")] public MontaRestApiModels_InboundForecast_InboundForecastEventCode? EventCode { get; set; } = default!;
    [JsonPropertyName("InboundForecastGroupId")] public string? InboundForecastGroupId { get; set; } = default!;
    [JsonPropertyName("InboundForecastGroupReference")] public string? InboundForecastGroupReference { get; set; } = default!;
    [JsonPropertyName("Created")] public System.DateTimeOffset? Created { get; set; } = default!;
}
