// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_ContactDetails
{
    [JsonPropertyName("Company")] public string? Company { get; set; } = default!;
    [JsonPropertyName("FirstName")] public string? FirstName { get; set; } = default!;
    [JsonPropertyName("MiddleName")] public string? MiddleName { get; set; } = default!;
    [JsonPropertyName("LastName")] public string? LastName { get; set; } = default!;
    [JsonPropertyName("Street")] public string Street { get; set; } = default!;
    [JsonPropertyName("HouseNumber")] public string? HouseNumber { get; set; } = default!;
    [JsonPropertyName("HouseNumberAddition")] public string? HouseNumberAddition { get; set; } = default!;
    [JsonPropertyName("PostalCode")] public string? PostalCode { get; set; } = default!;
    [JsonPropertyName("City")] public string City { get; set; } = default!;
    [JsonPropertyName("State")] public string? State { get; set; } = default!;
    [JsonPropertyName("CountryCode")] public string CountryCode { get; set; } = default!;
    [JsonPropertyName("PhoneNumber")] public string? PhoneNumber { get; set; } = default!;
    [JsonPropertyName("EmailAddress")] public string? EmailAddress { get; set; } = default!;
}
