// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModel_Efulfillment_Returns_Forecasts_Forecasts_models_ForecastLineTradeInProduct
{
    [JsonPropertyName("ForecastLineId")] public int? ForecastLineId { get; set; } = default!;
    [JsonPropertyName("ProductId")] public int? ProductId { get; set; } = default!;
    [JsonPropertyName("Ammount")] public int? Ammount { get; set; } = default!;
}
