// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_MessageWithShipperCode
{
    [JsonPropertyName("ShipperCode")] public string? ShipperCode { get; set; } = default!;
    [JsonPropertyName("Message")] public string? Message { get; set; } = default!;
}
