// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_StockMutation
{
    [JsonPropertyName("Created")] public System.DateTimeOffset? Created { get; set; } = default!;
    [JsonPropertyName("WarehouseGuid")] public string WarehouseGuid { get; set; } = default!;
    [JsonPropertyName("WarehouseLocationCode")] public string WarehouseLocationCode { get; set; } = default!;
    [JsonPropertyName("ProductSku")] public string? ProductSku { get; set; } = default!;
    [JsonPropertyName("Quantity")] public int Quantity { get; set; } = default!;
    [JsonPropertyName("Comment")] public string Comment { get; set; } = default!;
}
