// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Dto_ProductDto
{
    [JsonPropertyName("Product")] public MontaRESTApiModels_Product_Product? Product { get; set; } = default!;
}
