// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Product_WarehouseProductSettings
{
    [JsonPropertyName("MinimumStock")] public int? MinimumStock { get; set; } = default!;
    [JsonPropertyName("WarehouseId")] public string? WarehouseId { get; set; } = default!;
}
