// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRestApiModels_Orders_SplitOrders_SplitOrderRequestLine
{
    [JsonPropertyName("AmountToSplit")] public int? AmountToSplit { get; set; } = default!;
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
}
