// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_InvoiceLine
{
    [JsonPropertyName("Quantity")] public int Quantity { get; set; } = default!;
    [JsonPropertyName("Description")] public string Description { get; set; } = default!;
    [JsonPropertyName("AmountInclTax")] public double? AmountInclTax { get; set; } = default!;
    [JsonPropertyName("AmountExclTax")] public double? AmountExclTax { get; set; } = default!;
    [JsonPropertyName("TaxPercentage")] public double TaxPercentage { get; set; } = default!;
    [JsonPropertyName("TaxAmount")] public double? TaxAmount { get; set; } = default!;
    [JsonPropertyName("TaxDescription")] public string? TaxDescription { get; set; } = default!;
    [JsonPropertyName("ItemPriceInclTax")] public double? ItemPriceInclTax { get; set; } = default!;
    [JsonPropertyName("ItemPriceExclTax")] public double? ItemPriceExclTax { get; set; } = default!;
    [JsonPropertyName("Sku")] public string? Sku { get; set; } = default!;
    [JsonPropertyName("ChildSkus")] public System.Collections.Generic.List<string>? ChildSkus { get; set; } = default!;
    [JsonPropertyName("ShippingCost")] public bool ShippingCost { get; set; } = default!;
    [JsonPropertyName("Discount")] public bool Discount { get; set; } = default!;
    [JsonPropertyName("PaymentCosts")] public bool PaymentCosts { get; set; } = default!;
    [JsonPropertyName("Reference")] public string? Reference { get; set; } = default!;
}
