// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Return_ReturnInvalidReasonResponse
{
    [JsonPropertyName("ReturnInvalidReasons")] public System.Collections.Generic.List<MontaRESTApiModels_Return_ReturnInvalidReason>? ReturnInvalidReasons { get; set; } = default!;
}
