// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Product_ProductBarcode
{
    [JsonPropertyName("Barcode")] public string? Barcode { get; set; } = default!;
    [JsonPropertyName("Quantity")] public int? Quantity { get; set; } = default!;
    [JsonPropertyName("TypeId")] public int? TypeId { get; set; } = default!;
}
