// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaModelInterfaces_IConsumerDetails
{
    [JsonPropertyName("CommunicationLanguageCode")] public string? CommunicationLanguageCode { get; set; } = default!;
    [JsonPropertyName("DisplayMiddleLastName")] public string? DisplayMiddleLastName { get; set; } = default!;
    [JsonPropertyName("DisplayName")] public string? DisplayName { get; set; } = default!;
    [JsonPropertyName("HasDeviatingShippingInfo")] public bool? HasDeviatingShippingInfo { get; set; } = default!;
    [JsonPropertyName("InvoiceComment")] public string? InvoiceComment { get; set; } = default!;
    [JsonPropertyName("InvoiceContactDetails")] public MontaModelInterfaces_IContactDetails? InvoiceContactDetails { get; set; } = default!;
    [JsonPropertyName("InvoiceDebtorNumber")] public string? InvoiceDebtorNumber { get; set; } = default!;
    [JsonPropertyName("IsB2B")] public bool? IsB2B { get; set; } = default!;
    [JsonPropertyName("ShippingComment")] public string? ShippingComment { get; set; } = default!;
    [JsonPropertyName("ShippingContactDetails")] public MontaModelInterfaces_IContactDetails? ShippingContactDetails { get; set; } = default!;
}
