// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_Orders_OrderDeleteParameters
{
    [JsonPropertyName("Note")] public string Note { get; set; } = default!;
}
