// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
internal partial class MontaRESTApiModels_ShippingOptions_CheckOutProduct
{
    [JsonPropertyName("SKU")] public string? SKU { get; set; } = default!;
    [JsonPropertyName("LengthMm")] public int? LengthMm { get; set; } = default!;
    [JsonPropertyName("WidthMm")] public int? WidthMm { get; set; } = default!;
    [JsonPropertyName("HeightMm")] public int? HeightMm { get; set; } = default!;
    [JsonPropertyName("WeightGrammes")] public int? WeightGrammes { get; set; } = default!;
    [JsonPropertyName("Quantity")] public int? Quantity { get; set; } = default!;
}
