// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;
namespace ApiConsoleClient.Models;
[JsonConverter(typeof(JsonStringEnumConverter))]
internal enum MontaModel_Overhead_EorderType
{
    Unknown = 0,
    Test = 1,
    Fulfilment = 2,
    WMS = 3,
    MontashipV1 = 4,
    MontashipV2 = 5,
    AdministrativeReturn = 6,
    AdministrativeWholesale = 7,
    AdministrativeTTMail = 8,
    AdministrativeIntern = 9,
    MontashipV0 = 10,
}
